- id: '1575211081818'
  alias: Gameboy - Dunkelheit
  description: ''
  trigger:
  - entity_id: input_boolean.licht_innen_dunkelheit
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.plug_guestroom_computer
    state: 'on'
  action:
  - data: {}
    entity_id: scene.gameboy_an_dunkel
    service: scene.turn_on
  mode: single
- id: '1575655282938'
  alias: Katzentür - Video aufnehmen
  description: ''
  trigger:
  - entity_id: binary_sensor.magnet_door_cats_contact
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.people_home
    state: 'off'
  action:
  - data:
      duration: 20
      entity_id: camera.catdoor
      filename: /share/catdoor_{{ as_timestamp(now()) | int}}.mp4
      lookback: 5
    service: camera.record
  mode: single
- id: '1575655704902'
  alias: Präsenz - Ankommen - Eva
  description: ''
  trigger:
  - entity_id: person.eva
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.jens
    state: home
  action:
  - data:
      message: Eva kommt nach Hause
    service: notify.signal_jens
- id: '1576323625586'
  alias: Supervisor - Zertifikat erneuern
  description: ''
  trigger:
  - at: 03:30:00
    platform: time
  condition: []
  action:
  - data:
      addon: core_nginx_proxy
    service: hassio.addon_stop
  - data:
      addon: core_mosquitto
    service: hassio.addon_stop
  - data:
      addon: a0d7b954_bitwarden
    service: hassio.addon_stop
  - data:
      addon: a0d7b954_glances
    service: hassio.addon_stop
  - data:
      addon: a0d7b954_sonweb
    service: hassio.addon_stop
  - delay: 00:00:30
  - data:
      addon: core_letsencrypt
    service: hassio.addon_start
  - delay: 00:02:00
  - data:
      addon: core_letsencrypt
    service: hassio.addon_stop
  - delay: 00:00:30
  - data:
      addon: core_nginx_proxy
    service: hassio.addon_restart
  - data:
      addon: core_mosquitto
    service: hassio.addon_restart
  - data:
      addon: a0d7b954_bitwarden
    service: hassio.addon_restart
  - data:
      addon: a0d7b954_glances
    service: hassio.addon_restart
  - data:
      addon: a0d7b954_sonweb
    service: hassio.addon_restart
- id: '1576324741125'
  alias: Katzenklo - Büro
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_catlitter_office_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ now().timestamp() | int - states.input_datetime.last_usage_catlitter_office.attributes.timestamp
      | int > 300 }}'
  action:
  - entity_id: input_number.count_usage_catlitter
    service: input_number.increment
  - entity_id: input_number.count_usage_catlitter_office
    service: input_number.increment
  - data_template:
      datetime: '{{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d %H:%M:%S", true)
        }}

        '
    entity_id: input_datetime.last_usage_catlitter_office
    service: input_datetime.set_datetime
- id: '1576324905167'
  alias: Katzenklo - Flur
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_catlitter_hallway_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ now().timestamp() | int - states.input_datetime.last_usage_catlitter_hallway.attributes.timestamp
      | int > 300 }}'
  action:
  - entity_id: input_number.count_usage_catlitter
    service: input_number.increment
  - entity_id: input_number.count_usage_catlitter_hallway
    service: input_number.increment
  - data_template:
      datetime: '{{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d %H:%M:%S", true)
        }}

        '
    entity_id: input_datetime.last_usage_catlitter_hallway
    service: input_datetime.set_datetime
- id: '1576325083638'
  alias: Katzenklo - Gästezimmer
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_catlitter_guestroom_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ now().timestamp() | int - states.input_datetime.last_usage_catlitter_guestroom.attributes.timestamp
      | int > 300 }}'
  action:
  - entity_id: input_number.count_usage_catlitter
    service: input_number.increment
  - entity_id: input_number.count_usage_catlitter_guestroom
    service: input_number.increment
  - data_template:
      datetime: '{{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d %H:%M:%S", true)
        }}

        '
    entity_id: input_datetime.last_usage_catlitter_guestroom
    service: input_datetime.set_datetime
- id: '1577789351489'
  alias: Wecker - Wake up light
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == states(''input_datetime.alarm_wake_up_light'')[0:5]
      }}'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_enabled
    state: 'on'
  action:
  - entity_id: script.wakeup_light
    service: script.turn_on
- id: '1578663748318'
  alias: HACS - Add notification when update available
  description: ''
  trigger:
  - entity_id: sensor.hacs
    platform: state
  condition:
  - condition: template
    value_template: '{{ states(trigger.entity_id) != ''unknown''}}'
  - condition: template
    value_template: '{{ (states(trigger.entity_id) | float) != 0}}'
  action:
  - data_template:
      message: "{% for repo in state_attr(trigger.entity_id, 'repositories') %}\n\
        \  **{{ repo.display_name }}** _{{ repo[\"installed_version\"] }}_ -> _{{\
        \ repo[\"available_version\"] }}_\n{% endfor %}"
      notification_id: hacs_update_notification
      title: Updates pending in HACS
    service: persistent_notification.create
- id: '1581182751392'
  alias: Person - Eva - Stall verlassen
  description: ''
  trigger:
  - entity_id: person.eva
    event: leave
    platform: zone
    zone: zone.hof_holzapfel
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - entity_id: script.gaestezimmer_stehlampe_alarm_rot
    service: script.turn_on
- id: '1582480132470'
  alias: Katzentür - Video versenden
  description: ''
  trigger:
  - event_data:
      event_type: created
    event_type: folder_watcher
    platform: event
  condition:
  - condition: template
    value_template: '{{ ''catdoor_'' in trigger.event.data.file and ''/share'' in
      trigger.event.data.folder }}'
  action:
  - delay: 00:00:05
  - data_template:
      filename: '{{ trigger.event.data.path }}'
    service: shell_command.catdoor_copy_video
  - delay: 00:00:02
  - data:
      data:
        video:
        - caption: Katzentür
          file: /share/catdoor.mp4
      message: Hier ist das neueste Video der Katzentür.
      title: Katzentür
    service: notify.signal_all
  - delay: 00:00:15
  - data_template:
      filename: '{{ trigger.event.data.path }}'
    service: shell_command.catdoor_remove_video
  mode: single
- id: '1582969948699'
  alias: CSGO - Freezetime beginnt - Stehlampe
  description: ''
  trigger:
  - event_data: {}
    event_type: csgo_round_freeze
    platform: event
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - data: {}
    entity_id: script.csgo_freezetime_stehlampe
    service: script.turn_on
- id: '1582971262781'
  alias: CSGO - Runde beginnt oder Spiel endet - Stehlampe
  description: ''
  trigger:
  - event_data: {}
    event_type: csgo_round_started
    platform: event
  - event_data: {}
    event_type: csgo_game_stopped
    platform: event
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - data: {}
    entity_id: script.csgo_rundenstart_spielende_stehlampe
    service: script.turn_on
- id: '1582971443403'
  alias: CSGO - Bombe gelegt - Stehlampe
  description: ''
  trigger:
  - event_data: {}
    event_type: csgo_bomb_planted
    platform: event
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - data: {}
    entity_id: script.csgo_bombegelegt_stehlampe
    service: script.turn_on
- id: '1582971518136'
  alias: CSGO - Bombe explodiert - Stehlampe
  description: ''
  trigger:
  - event_data: {}
    event_type: csgo_bomb_exploded
    platform: event
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - data: {}
    entity_id: script.csgo_bombeexplodiert_stehlampe
    service: script.turn_on
- id: '1582971569875'
  alias: CSGO - Bombe entschärft - Stehlampe
  description: ''
  trigger:
  - event_data: {}
    event_type: csgo_bomb_defused
    platform: event
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - data: {}
    entity_id: script.csgo_bombeentschaeft_stehlampe
    service: script.turn_on
- id: '1583018895328'
  alias: CSGO - Rundenende - Stehlampe
  description: ''
  trigger:
  - event_type: csgo_round_ended
    platform: event
  condition:
  - condition: state
    entity_id: light.guestroom_standinglight
    state: 'on'
  action:
  - data: {}
    service: script.csgo_rundenende_stehlampe
- id: '1588948500578'
  alias: Wecker - Rolladen auf Spalt
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == states(''input_datetime.alarm_open_shutters'')[0:5]
      }}'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_enabled
    state: 'on'
  action:
  - data: {}
    entity_id: script.cover_bedroom_ajar
    service: script.turn_on
- id: '1589642700574'
  alias: Schlafen - Lichtschutz
  description: Rolläden 30 Minuten vor Sonnenaufgang schließen
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id:
    - cover.bedroom
    - cover.guestroom
    - cover.office
    - cover.couch
    - cover.patio
    - cover.dining
    - cover.kitchen
    service: cover.close_cover
- id: '1589820839263'
  alias: Wiegen Jens - Erinnerung senden
  description: ''
  trigger:
  - entity_id: light.shower_ceiling
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.jens_wiegen_erinnerung_gesendet
    state: 'off'
  - after: 05:00:00
    before: '12:00:00'
    condition: time
  action:
  - data: {}
    entity_id: input_boolean.jens_wiegen_erinnerung_gesendet
    service: input_boolean.turn_on
  - data:
      message: Guten Morgen, es ist Zeit Dich zu wiegen!
    service: notify.mobile_app_pixel_5
- id: '1589820924653'
  alias: Wiegen Jens - Erinnerung zuruecksetzen
  description: ''
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.jens_wiegen_erinnerung_gesendet
    service: input_boolean.turn_off
- id: '1606053818958'
  alias: Licht Flur - An
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.hallway_light
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.hallway_entrance
  - service: light.turn_on
    data: {}
    entity_id: light.hallway_center
  mode: single
- id: '1606053837867'
  alias: Licht Flur - Aus
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.hallway_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.hallway_entrance
  - service: light.turn_off
    data: {}
    entity_id: light.hallway_center
  mode: single
- id: '1612189008531'
  alias: Jens Arbeit - Nächster Termin - 5 Minuten
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.calendar_jens_work_next_event
    from: '5'
    to: '4'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      entity_id:
      - media_player.guestroom
  - delay: 00:00:02
  - service: tts.cloud_say
    data:
      entity_id: media_player.guestroom
      message: Dein nächster Termin startet in fünf Minuten
      options:
        gender: female
      language: de-DE
  mode: single
- id: '1612189317632'
  alias: Jens Arbeit - Nächster Termin - 1 Minute
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.calendar_jens_work_next_event
    from: '1'
    to: '0'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      entity_id:
      - media_player.guestroom
  - delay: 00:00:02
  - service: tts.cloud_say
    data:
      entity_id: media_player.guestroom
      message: Dein nächster Termin startet in einer Minute
      options:
        gender: female
      language: de-DE
  mode: single
