# load all default setup
default_config:

homeassistant:
  packages: !include_dir_named packages

  allowlist_external_dirs:
    - /tmp
    - /share

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# support video streams
stream:

# record to mariadb
recorder:
  purge_keep_days: 30
  db_url: !secret recorder_db_url
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.date_time
    entity_globs:
      - device_tracker.unifi_*_default

# include hacs themes
frontend:
  themes: !include_dir_merge_named themes

# activate webhooks
webhook:

logger:
  default: error

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 10.211.112.231  # control running traefik proxy
