
# load all default setup
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml

  whitelist_external_dirs:
    - /tmp
    - /share

# text to speech
tts: !include tts.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# support video streams
stream:

# check for updates and send anonymous component usage stats
updater:
  include_used_components: true

# record to mariadb
recorder:
  purge_keep_days: 30
  db_url: !secret recorder_db_url
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.date_time
      - sensor.seconds_of_day
    entity_globs:
      - device_tracker.unifi_*_default
      - device_tracker.miband_jens
      - device_tracker.miband_eva

# include hacs themes
frontend:
  themes: !include_dir_merge_named themes

# activate webhooks
webhook:

logger:
  default: error
