# shelly 2.5
# 22

substitutions:
  id: light_livingroom_ceiling
  friendly_name: Deckenlicht Wohnzimmer
  update_throttle: 30s

  name_a: Deckenlicht Wohnzimmer

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_light_binary_a.yaml
