# shelly 2.5
# 29

substitutions:
  id: light_office_jens_ceiling
  friendly_name: Deckenlicht Büro Jens
  update_throttle: 30s

  name_a: Deckenlicht Büro Jens

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_light_binary_a.yaml
