# shelly 1
# 01

substitutions:
  id: light_shower_ceiling
  friendly_name: Deckenlicht Dusche
  update_throttle: 30s

  name_a: Deckenlicht Dusche

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly1.yaml
  template_a: !include common/template_light_binary_a.yaml
