homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages/

  auth_providers:
  - type: homeassistant

# enable default components
default_config:

# enable to auth provider
auth:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# check for updates and send anonymous component usage stats
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

http:
  base_url: !secret base_url

recorder:
  purge_keep_days: 30
  purge_interval: 1
  db_url: !secret recorder_db_url
  include:
    domains:
      - sensor
      - switch
      - light
      - cover
      - vacuum
      - media_player
      - input_select
      - device_tracker
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_number
  exclude:
    entities:
    - sun.sun
    - sensor.date

influxdb:
  host: influxdb
  port: 8086
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: home_assistant
  ssl: false
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - switch
      - light
      - cover
      - vacuum
      - media_player
      - input_select
      - device_tracker
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_number
  exclude:
    entities:
    - sun.sun
    - sensor.date
  tags:
    instance: production
    source: homeassistant

cloud: !include cloud.yaml
tts: !include tts.yaml
zone: !include zones.yaml

lovelace:
  mode: yaml

panel_iframe:
  paperless:
    title: Paperless
    url: https://home.schoenbuchallee.de:8001
    icon: mdi:newspaper
  traccar:
    title: Traccar
    url: https://home.schoenbuchallee.de:8002
    icon: mdi:satellite-variant
  synology:
    title: Synology
    url: https://home.schoenbuchallee.de:5000
    icon: mdi:nas
  grafana:
    title: Grafana
    url: http://ship:3000
    icon: mdi:chart-areaspline
  chronograf:
    title: Chronograf
    url: http://ship:8888
    icon: mdi:clock-outline
