homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages/

  auth_providers:
  - type: homeassistant
  - type: legacy_api_password

# enable to auth provider
auth:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# check for updates and send anonymous component usage stats
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# enable sun component
sun:

http:
  base_url: !secret base_url
  api_password: !secret http_password

recorder:
  purge_keep_days: 30
  purge_interval: 1
  db_url: !secret recorder_db_url
  include:
    domains:
      - sensor
      - switch
      - light
      - cover
      - media_player
      - input_select
      - device_tracker
      - binary_sensor
  exclude:
    entities:
    - sun.sun
    - sensor.date

influxdb:
  host: influxdb
  port: 8086
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: home_assistant
  ssl: false
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - switch
      - light
      - cover
      - media_player
      - input_select
      - device_tracker
      - binary_sensor
  exclude:
    entities:
    - sun.sun
    - sensor.date
  tags:
    instance: production
    source: homeassistant

cloud: !include cloud.yaml
tts: !include tts.yaml
zone: !include zones.yaml

# https://github.com/custom-components/custom_updater
custom_updater:
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
