- platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  language: 'de'
- platform: amazon_polly
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  language: 'de'
  aws_access_key_id: !secret aws_access_key_id
  aws_secret_access_key: !secret aws_secret_access_key
  region_name: eu-central-1
  voice: Marlene
