title: Wohnung

# custom components
# weather card: https://community.home-assistant.io/t/custom-animated-weather-card-for-lovelace/58338

resources:
  - url: /local/custom_ui/weather-card.js
    type: js

views:
  - !include lovelace/00_light_and_cover.yaml
  - !include lovelace/10_garden_and_plants.yaml
  - !include lovelace/20_movie_and_tv.yaml
  - !include lovelace/30_music.yaml
  - !include lovelace/40_weather.yaml
  - !include lovelace/50_devices.yaml
  - !include lovelace/60_car_and_travel.yaml
  - !include lovelace/70_laundry.yaml
  - !include lovelace/80_system.yaml
  - !include lovelace/90_automation.yaml
