[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  filePath = "/var/log/traefik.log"
  level = "info"
  format = "json"

[entrypoints]

  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"

  [accessLog.filters]
    statusCodes = ["200", "300-302"]
    retryAttempts = true
    minDuration = "10ms"

  [accessLog.fields]
    defaultmode = "keep"
    [accessLog.fields.names]
      "clientUsername" = "drop"

    [accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "User-Agent" = "redact"
        "Authorization" = "drop"
        "Content-Type" = "keep"

[api]
  dashboard = true

[ping]

[providers]
  [providers.file]
    directory = "/etc/traefik/conf.d"
    watch = true

  [providers.docker]
    watch = true
    exposedByDefault = false

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "letsencrypt@jensnistler.de"
      storage = "/etc/traefik/acme.json"

      [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "http"
