SIMULATE = True

# watering automation
AUTOMATION_WATERING_SHORT = 'input_boolean.automation_watering_short'
AUTOMATION_WATERING_LONG = 'input_boolean.automation_watering_long'
AUTOMATION_WATERING_SHORT_NIGHT = 'input_boolean.automation_watering_short_night'
AUTOMATION_WATERING_LONG_NIGHT = 'input_boolean.automation_watering_long_night'
AUTOMATION_WATERING_NIGHT_START = 'input_datetime.automation_watering_night_start'

AUTOMATION_WATERING_SHORT_AREA_ONE = 'input_number.automation_watering_short_duration_area_1'
AUTOMATION_WATERING_SHORT_AREA_TWO = 'input_number.automation_watering_short_duration_area_2'
AUTOMATION_WATERING_SHORT_AREA_THREE = 'input_number.automation_watering_short_duration_area_3'
AUTOMATION_WATERING_LONG_AREA_ONE = 'input_number.automation_watering_long_duration_area_1'
AUTOMATION_WATERING_LONG_AREA_TWO = 'input_number.automation_watering_long_duration_area_2'
AUTOMATION_WATERING_LONG_AREA_THREE = 'input_number.automation_watering_long_duration_area_3'

WATERING_AREA_1 = 'light.bewasserung__sprenkler'
WATERING_AREA_2 = 'light.bewasserung__raketen'
WATERING_AREA_3 = 'light.bewasserung__busche'
