blueprint:
  name: Badezimmer Belüftung 
  description: Steuert die Lüfter in den Badezimmern
  source_url: https://github.com/lociii/homeassistant-config/blob/master/blueprints/automation/bathroom_ventilation.yaml
  domain: automation
  input:
    fan:
      name: Lüfter
      selector:
        entity:
          domain: fan
    helper:
      name: Helfer
      selector:
        entity:
          domain: input_boolean
    light:
      name: Licht
      selector:
        entity:
          multiple: true
          domain: light

trigger:
  - platform: state
    entity_id: !input light
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - platform: state
    entity_id: !input light
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: time_pattern
    minutes: "/5"

action:
  - if:
    # light has been turned on or off
    - condition: template
      value_template: "{{ trigger.platform == 'state' }}"
    then:
      - if:
        # light is on
        - condition: state
          state: "on"
          match: any
          entity_id: !input light
        then:
          # turn fan on
          - service: fan.turn_on
            entity_id: !input fan
          # turn occupancy mode on
          - service: input_boolean.turn_on
            entity_id: !input helper
        else:
          # turn fan off
          - service: fan.turn_off
            entity_id: !input fan
          # turn occupancy mode off
          - service: input_boolean.turn_off
            entity_id: !input helper
    else:
      - if:
        # not on occupancy mode
        - condition: state
          state: "off"
          entity_id: !input helper
        then:
          - if:
            # not sleeping, toggle every five minutes
            - condition: state
              entity_id: input_boolean.sleeping
              state: "off"
            then:
              - service: fan.toggle
                entity_id: !input fan
            # turn on for the night
            else:
              - service: fan.turn_on
                entity_id: !input fan
