blueprint:
  name: Badezimmer Belüftung 
  description: Steuert die Lüfter in den Badezimmern
  source_url: https://github.com/lociii/homeassistant-config/blob/master/blueprints/automation/bathroom_ventilation.yaml
  domain: automation
  input:
    fan:
      name: Lüfter
      selector:
        entity:
          filter:
            domain: fan
    helper:
      name: Helfer
      selector:
        entity:
          filter:
            domain: input_boolean
    light:
      name: Licht
      selector:
        entity:
          multiple: true
          filter:
            domain: light

trigger:
  - trigger: state
    entity_id: !input light
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - trigger: state
    entity_id: !input light
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - trigger: time_pattern
    minutes: "/5"

action:
  # light status has changed
  - if:
    - condition: template
      value_template: "{{ trigger.platform == 'state' }}"
    then:
      - if:
        # light is on
        - condition: state
          state: "on"
          match: any
          entity_id: !input light
        then:
          # turn occupancy mode on
          - action: input_boolean.turn_on
            entity_id: !input helper
        else:
          # turn occupancy mode off
          - action: input_boolean.turn_off
            entity_id: !input helper
  # set fan status
  - if:
    # on occupancy mode
    - condition: state
      state: "on"
      entity_id: !input helper
    then:
      # turn on
      - action: fan.turn_on
        entity_id: !input fan
    else:
      - if:
        # not sleeping, toggle every five minutes
        - condition: state
          entity_id: input_boolean.sleeping
          state: "off"
        then:
          - action: fan.toggle
            entity_id: !input fan
        # turn on for the night
        else:
          - action: fan.turn_on
            entity_id: !input fan
