blueprint:
  name: Sensor schaltet Licht
  description: Betätigung eines Sensors schaltet eines oder mehrere Lichter an/aus
  source_url: https://github.com/lociii/homeassistant-config/blob/master/blueprints/automation/sensor_toggles_light.yaml
  domain: automation
  input:
    sensor:
      name: Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
    target:
      name: Ziel
      selector:
        target:
          entity:
            domain: light

mode: single
max_exceeded: silent

trigger:
  trigger: state
  entity_id: !input sensor
  from: "off"
  to: "on"

action:
  - action: light.toggle
    target: !input target
