packages:
  device: !include device_sp111.yaml

# v3.4 is the same as a sp111 v1.4 but with two relays
# we'll just add a second output for the USB ports

output:
  # switched output b (USB)
  - platform: gpio
    pin: ${actor_pin_usb}
    id: "${id}_actor_b"
