switch:
  # actual switch powering the motor, direction is defined by setting output_1 to "up" or "down"
  - platform: gpio
    id: "${id}_cover_${output_1}"
    name: "${id} cover ${output_1}"
    pin:
      number: GPIO15
  # actual switch powering the motor, direction is defined by setting output_2 to "up" or "down"
  - platform: gpio
    id: "${id}_cover_${output_2}"
    name: "${id} cover ${output_2}"
    pin:
      number: GPIO4

  - platform: template
    name: "Programming mode on"
    turn_on_action:
    - switch.turn_on: ${id}_cover_${output_1}
    - switch.turn_on: ${id}_cover_${output_2}
    - delay: 10s
    - switch.turn_off: ${id}_cover_${output_1}
    - switch.turn_off: ${id}_cover_${output_2}

  - platform: template
    name: "Define endstop ${output_1}"
    turn_on_action:
    - switch.turn_on: ${id}_cover_${output_1}
    - switch.turn_on: ${id}_cover_${output_2}
    - delay: 2s
    - switch.turn_off: ${id}_cover_${output_1}
    - switch.turn_off: ${id}_cover_${output_2}
    - delay: 0.5s
    - switch.turn_on: ${id}_cover_${output_1}
    - delay: 2s
    - switch.turn_off: ${id}_cover_${output_1}

  - platform: template
    name: "Define endstop ${output_2}"
    turn_on_action:
    - switch.turn_on: ${id}_cover_${output_1}
    - switch.turn_on: ${id}_cover_${output_2}
    - delay: 2s
    - switch.turn_off: ${id}_cover_${output_1}
    - switch.turn_off: ${id}_cover_${output_2}
    - delay: 0.5s
    - switch.turn_on: ${id}_cover_${output_2}
    - delay: 2s
    - switch.turn_off: ${id}_cover_${output_2}
