switch:
  - platform: output
    id: "${id}_switch_a"
    name: "${name_a}"
    output: "${id}_actor_a"

    restore_mode: ${restore_mode_a}

    on_turn_on:
      - light.turn_on: ${id}_relay_state_light
    on_turn_off:
      - light.turn_off: ${id}_relay_state_light
