camera:
  - platform: generic
    name: catdoor
    still_image_url: !secret camera_catdoor_still_image
    stream_source: !secret camera_catdoor_stream_source
    verify_ssl: false
    framerate: 15

automation:
  - alias: record_catdoor
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.magnet_door_cats_contact
        from: 'off'
        to: 'on'
    action:
      - service: camera.record
        entity_id: camera.catdoor
        data:
          duration: 30
          filename: '/videos/{{ entity_id }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
