switch:
  platform: command_line
  switches:
    heating_on:
      command_on: curl -X POST "http://10.211.112.138/switch/turn_pre-heating_on/turn_on"
      command_off: curl -X POST "http://10.211.112.138/switch/turn_pre-heating_on/turn_off"
      friendly_name: Standheizung an
    heating_off:
      command_on: curl -X POST "http://10.211.112.138/switch/turn_pre-heating_off/turn_on"
      command_off: curl -X POST "http://10.211.112.138/switch/turn_pre-heating_off/turn_off"
      friendly_name: Standheizung aus

scene:
  - name: car_heating_on
    entities:
      switch.heating_on: true
  - name: car_heating_off
    entities:
      switch.heating_off: true

script:
  timer_on_off:
    sequence:
      - delay:
          seconds: 5
      - service: homeassistant.turn_off
        data:
          entity_id: switch.heating_on
  timer_off_off:
    sequence:
      - delay:
          seconds: 5
      - service: homeassistant.turn_off
        data:
          entity_id: switch.heating_off

automation:
  - trigger:
      platform: state
      entity_id: switch.heating_on
      to: 'on'
    action:
      service: script.turn_on
      entity_id: script.timer_on_off
  - trigger:
      platform: state
      entity_id: switch.heating_off
      to: 'on'
    action:
      service: script.turn_on
      entity_id: script.timer_off_off
