binary_sensor:
  # cat litter office
  - platform: mqtt
    name: occupancy_catlitter_office
    state_topic: zigbee2mqtt/occupancy_catlitter_office
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: motion
  # cat litter hallway
  - platform: mqtt
    name: occupancy_catlitter_hallway
    state_topic: zigbee2mqtt/occupancy_catlitter_hallway
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: motion
  # cat litter guestroom
  - platform: mqtt
    name: occupancy_catlitter_guestroom
    state_topic: zigbee2mqtt/occupancy_catlitter_guestroom
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: motion

sensor:
  # cat litter office
  - platform: mqtt
    name: illuminance_catlitter_office
    state_topic: zigbee2mqtt/occupancy_catlitter_office
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: lx
    device_class: illuminance
    value_template: "{{ value_json.illuminance }}"
  - platform: mqtt
    name: battery_occupancy_catlitter_office
    state_topic: zigbee2mqtt/occupancy_catlitter_office
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    device_class: battery
    value_template: "{{ value_json.battery }}"
  # cat litter hallway
  - platform: mqtt
    name: illuminance_catlitter_hallway
    state_topic: zigbee2mqtt/occupancy_catlitter_hallway
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: lx
    device_class: illuminance
    value_template: "{{ value_json.illuminance }}"
  - platform: mqtt
    name: battery_occupancy_catlitter_hallway
    state_topic: zigbee2mqtt/occupancy_catlitter_hallway
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    device_class: battery
    value_template: "{{ value_json.battery }}"
  # cat litter guestroom
  - platform: mqtt
    name: illuminance_catlitter_guestroom
    state_topic: zigbee2mqtt/occupancy_catlitter_guestroom
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: lx
    device_class: illuminance
    value_template: "{{ value_json.illuminance }}"
  - platform: mqtt
    name: battery_occupancy_catlitter_guestroom
    state_topic: zigbee2mqtt/occupancy_catlitter_guestroom
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    device_class: battery
    value_template: "{{ value_json.battery }}"

  - platform: template
    sensors:
      usage_catlitter_office:
        value_template: '{% if states("input_number.count_usage_catlitter_office") | int > 0 %}{{ states("input_number.count_usage_catlitter_office") | int }} Mal, zuletzt {{ as_timestamp(states("input_datetime.last_usage_catlitter_office")) | timestamp_custom("%d.%m.%Y %H:%M") }}{% else %}Nicht benutzt{% endif %}'
      usage_catlitter_hallway:
        value_template: '{% if states("input_number.count_usage_catlitter_hallway") | int > 0 %}{{ states("input_number.count_usage_catlitter_hallway") | int }} Mal, zuletzt {{ as_timestamp(states("input_datetime.last_usage_catlitter_hallway")) | timestamp_custom("%d.%m.%Y %H:%M") }}{% else %}Nicht benutzt{% endif %}'
      usage_catlitter_guestroom:
        value_template: '{% if states("input_number.count_usage_catlitter_guestroom") | int > 0 %}{{ states("input_number.count_usage_catlitter_guestroom") | int }} Mal, zuletzt {{ as_timestamp(states("input_datetime.last_usage_catlitter_guestroom")) | timestamp_custom("%d.%m.%Y %H:%M") }}{% else %}Nicht benutzt{% endif %}'

input_datetime:
  last_usage_catlitter_office:
    has_date: true
    has_time: true
  last_usage_catlitter_hallway:
    has_date: true
    has_time: true
  last_usage_catlitter_guestroom:
    has_date: true
    has_time: true

input_number:
  count_usage_catlitter:
    initial: 0
    min: 0
    max: 100
    step: 1
  count_usage_catlitter_office:
    initial: 0
    min: 0
    max: 100
    step: 1
  count_usage_catlitter_hallway:
    initial: 0
    min: 0
    max: 100
    step: 1
  count_usage_catlitter_guestroom:
    initial: 0
    min: 0
    max: 100
    step: 1

automation:
  - alias: catlitter_office
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_catlitter_office
        from: 'off'
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ as_timestamp(now()) | int - as_timestamp(states("input_datetime.last_usage_catlitter_office")) | int > 300 }}'
    action:
      - service: input_number.increment
        entity_id: input_number.count_usage_catlitter
      - service: input_number.increment
        entity_id: input_number.count_usage_catlitter_office
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_usage_catlitter_office
        data_template:
          datetime: >
            {{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d %H:%M:%S", true) }}

  - alias: catlitter_hallway
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_catlitter_hallway
        from: 'off'
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ as_timestamp(now()) | int - as_timestamp(states("input_datetime.last_usage_catlitter_hallway")) | int > 300 }}'
    action:
      - service: input_number.increment
        entity_id: input_number.count_usage_catlitter
      - service: input_number.increment
        entity_id: input_number.count_usage_catlitter_hallway
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_usage_catlitter_hallway
        data_template:
          datetime: >
            {{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d %H:%M:%S", true) }}

  - alias: catlitter_guestroom
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_catlitter_guestroom
        from: 'off'
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ as_timestamp(now()) | int - as_timestamp(states("input_datetime.last_usage_catlitter_guestroom")) | int > 300 }}'
    action:
      - service: input_number.increment
        entity_id: input_number.count_usage_catlitter
      - service: input_number.increment
        entity_id: input_number.count_usage_catlitter_guestroom
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_usage_catlitter_guestroom
        data_template:
          datetime: >
            {{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d %H:%M:%S", true) }}

script:
  catlitter_reset_all:
    sequence:
      - service: input_number.set_value
        entity_id: input_number.count_usage_catlitter
        data:
          value: 0
      - service: input_number.set_value
        entity_id: input_number.count_usage_catlitter_office
        data:
          value: 0
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_usage_catlitter_office
        data:
          datetime: "1970-01-01 00:00:00"
      - service: input_number.set_value
        entity_id: input_number.count_usage_catlitter_hallway
        data:
          value: 0
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_usage_catlitter_hallway
        data:
          datetime: "1970-01-01 00:00:00"
      - service: input_number.set_value
        entity_id: input_number.count_usage_catlitter_guestroom
        data:
          value: 0
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_usage_catlitter_guestroom
        data:
          datetime: "1970-01-01 00:00:00"
