docker_monitor:
  containers:
    - appdaemon
    - backup
    - chronograf
    - ftp
    - glances
    - grafana
    - homeassistant
    - influxdb
    - letsencrypt
    - mosquitto
    - nginx
    - paperless_consumer
    - paperless_webserver
    - postgresql
    - traccar
    - traccar_db
  monitored_conditions:
    - utilization_version
    - container_status
    - container_uptime
    - container_image
    - container_memory_usage
    - container_memory_percentage_usage
    - container_cpu_percentage_usage
    - container_network_speed_up
    - container_network_speed_down
    - container_network_total_up
    - container_network_total_down

automation:
  - alias: 'Start letsencrypt every night to renew certificate'
    trigger:
      platform: time
      at: '04:00:00'
    action:
      service: switch.turn_on
      data:
        entity_id:
          - switch.docker_letsencrypt
  - alias: 'Stop nginx to pick up new certificate'
    trigger:
      platform: time
      at: '04:15:00'
    action:
      service: switch.turn_off
      data:
        entity_id:
          - switch.docker_nginx
  - alias: 'Start nginx with new certificate'
    trigger:
      platform: time
      at: '04:16:00'
    action:
      service: switch.turn_on
      data:
        entity_id:
          - switch.docker_nginx
