switch:
  # TP-Link HS110 power plug
  - platform: tplink
    name: power_plug_dryer
    host: !secret tplink_power_plug_dryer

input_select:
  # status selector
  dryer_status:
    initial: Aus
    icon: mdi:power
    options:
    - "Aus"
    - "Aktiv"
    - "Fertig"

sensor:
  - platform: template
    # define the triggers that update this template sensor
    entity_id:
    - switch.power_plug_dryer
    - input_select.dryer_status
    sensors:
      # define current power attribute as seperate sensor from power plug
      dryer_current_power_usage:
        value_template: '{{ states.switch.power_plug_dryer.attributes.current_power_w }}'
        unit_of_measurement: 'W'
      # define input select read only sensor
      dryer_status_text:
        value_template: '{{ states.input_select.dryer_status.state }}'

  # define history sensor for mean power usage of last 5 minutes
  - platform: statistics
    name: dryer_consumption_last_5_mins
    entity_id: sensor.dryer_current_power_usage
    max_age:
      minutes: 5
