# https://www.home-assistant.io/components/sensor.glances/

sensor:
  - platform: glances
    name: glances
    host: glances
    version: 3
    resources:
    - disk_free
    - disk_use_percent
    - memory_free
    - memory_use_percent
    - swap_free
    - swap_use_percent
    - process_total
    - processor_load
    - cpu_temp
    - docker_active
    - docker_cpu_use
    - docker_memory_use
