mqtt:
  broker: mosquitto
  username: !secret mosquitto_user
  password: !secret mosquitto_password
  client_id: homeassistant
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

switch:
  - platform: mqtt
    name: zigbee2mqtt_permit_join
    state_topic: zigbee2mqtt/bridge/config/permit_join
    command_topic: zigbee2mqtt/bridge/config/permit_join
    availability_topic: zigbee2mqtt/bridge/state
    payload_off: "false"
    payload_on: "true"
    state_off: "false"
    state_on: "true"

zigbee2mqtt_networkmap:

automation:
  - id: update_networkmap
    alias: 'Zigbee Map aktualisieren'  
    hide_entity: true  
    trigger:
      platform: time_pattern
      minutes: '/10'
      seconds: 00
    action:
      service: zigbee2mqtt_networkmap.update


#   # water leakage one
#   - platform: mqtt
#     name: water_leakage_one
#     state_topic: zigbee2mqtt/water_leak_one
#     availability_topic: zigbee2mqtt/bridge/state
#     payload_on: true
#     payload_off: false
#     value_template: "{{ value_json.water_leak }}"
#     device_class: moisture
#   # water leakage one
#   - platform: mqtt
#     name: water_leakage_two
#     state_topic: zigbee2mqtt/water_leak_two
#     availability_topic: zigbee2mqtt/bridge/state
#     payload_on: true
#     payload_off: false
#     value_template: "{{ value_json.water_leak }}"
#     device_class: moisture
