mqtt:
  broker: mosquitto
  username: !secret mosquitto_user
  password: !secret mosquitto_password
  client_id: homeassistant
  discovery: false
  birth_message:
    topic: 'zigbee2mqtt/bridge/state'
    payload: 'online'
  will_message:
    topic: 'zigbee2mqtt/bridge/state'
    payload: 'offline'

switch:
  # allow joining new devices on zigbee2mqtt
  - platform: mqtt
    name: zigbee2mqtt_permit_join
    state_topic: zigbee2mqtt/bridge/config/permit_join
    command_topic: zigbee2mqtt/bridge/config/permit_join
    availability_topic: zigbee2mqtt/bridge/state
    payload_off: "false"
    payload_on: "true"
    state_off: "false"
    state_on: "true"
  # power plug entertainment living room
  - platform: mqtt
    name: osram_plug_entertainment
    state_topic: zigbee2mqtt/osram_plug_entertainment
    availability_topic: zigbee2mqtt/bridge/state
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: zigbee2mqtt/osram_plug_entertainment/set
  # power plug reading light living room
  - platform: mqtt
    name: osram_plug_readinglight
    state_topic: zigbee2mqtt/osram_plug_readinglight
    availability_topic: zigbee2mqtt/bridge/state
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: zigbee2mqtt/osram_plug_readinglight/set
  # power plug floor lamp guestroom
  - platform: mqtt
    name: osram_plug_guestroom
    state_topic: zigbee2mqtt/osram_plug_guestroom
    availability_topic: zigbee2mqtt/bridge/state
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: zigbee2mqtt/osram_plug_guestroom/set
  # power plug coffee machine kitchen
  - platform: mqtt
    name: osram_plug_kitchen
    state_topic: zigbee2mqtt/osram_plug_kitchen
    availability_topic: zigbee2mqtt/bridge/state
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: zigbee2mqtt/osram_plug_kitchen/set

binary_sensor:
  # door sensor patio
  - platform: mqtt
    name: door_sensor_patio
    state_topic: zigbee2mqtt/door_sensor_patio
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: door
  # window sensor kitchen
  - platform: mqtt
    name: door_sensor_kitchen
    state_topic: zigbee2mqtt/door_sensor_kitchen
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: door
  # window sensor bedroom
  - platform: mqtt
    name: door_sensor_guestroom
    state_topic: zigbee2mqtt/door_sensor_guestroom
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: door
  # window sensor bedroom
  - platform: mqtt
    name: door_sensor_bedroom
    state_topic: zigbee2mqtt/door_sensor_bedroom
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: door
  # window sensor office
  - platform: mqtt
    name: door_sensor_office
    state_topic: zigbee2mqtt/door_sensor_office
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: door
  # door sensor entrance
  - platform: mqtt
    name: door_sensor_entrance
    state_topic: zigbee2mqtt/door_sensor_entrance
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: door
  # water leakage one
  - platform: mqtt
    name: water_leakage_one
    state_topic: zigbee2mqtt/water_leak_one
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: moisture
  # water leakage one
  - platform: mqtt
    name: water_leakage_two
    state_topic: zigbee2mqtt/water_leak_two
    availability_topic: zigbee2mqtt/bridge/state
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: moisture

light:
  - platform: mqtt
    schema: json
    name: garden_one
    state_topic: zigbee2mqtt/light_garden_one
    availability_topic: zigbee2mqtt/bridge/state
    brightness: true
    xy: true
    command_topic: zigbee2mqtt/light_garden_one/set
  - platform: mqtt
    schema: json
    name: garden_two
    state_topic: zigbee2mqtt/light_garden_two
    availability_topic: zigbee2mqtt/bridge/state
    brightness: true
    xy: true
    command_topic: zigbee2mqtt/light_garden_two/set
  - platform: mqtt
    schema: json
    name: garden_three
    state_topic: zigbee2mqtt/light_garden_three
    availability_topic: zigbee2mqtt/bridge/state
    brightness: true
    xy: true
    command_topic: zigbee2mqtt/light_garden_three/set

sensor:
  # window sensor patio
  - platform: mqtt
    name: door_sensor_patio_battery
    state_topic: zigbee2mqtt/door_sensor_patio
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # window sensor kitchen
  - platform: mqtt
    name: door_sensor_kitchen_battery
    state_topic: zigbee2mqtt/door_sensor_kitchen
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # window sensor bedroom
  - platform: mqtt
    name: door_sensor_guestroom_battery
    state_topic: zigbee2mqtt/door_sensor_guestroom
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # window sensor bedroom
  - platform: mqtt
    name: door_sensor_bedroom_battery
    state_topic: zigbee2mqtt/door_sensor_bedroom
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # window sensor office
  - platform: mqtt
    name: door_sensor_office_battery
    state_topic: zigbee2mqtt/door_sensor_office
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # door sensor entrance
  - platform: mqtt
    name: door_sensor_entrance_battery
    state_topic: zigbee2mqtt/door_sensor_entrance
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # water leakage sensor one
  - platform: mqtt
    name: water_leakage_one_battery
    state_topic: zigbee2mqtt/water_leak_one
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # water leakage sensor two
  - platform: mqtt
    name: water_leakage_two_battery
    state_topic: zigbee2mqtt/water_leak_two
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
      - linkquality
  # outdoor temperature sensor
  - platform: mqtt
    name: weather_outdoor_temperature
    state_topic: zigbee2mqtt/weather_outdoor
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"
    json_attributes:
      - battery
      - voltage
      - linkquality
  - platform: mqtt
    name: weather_outdoor_humidity
    state_topic: zigbee2mqtt/weather_outdoor
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    value_template: "{{ value_json.humidity }}"
  - platform: mqtt
    name: weather_outdoor_pressure
    state_topic: zigbee2mqtt/weather_outdoor
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "Pa"
    value_template: "{{ value_json.pressure }}"
  - platform: template
    sensors:
      weather_outdoor_battery:
        value_template: '{{ states.sensor.weather_outdoor_temperature.attributes.battery }}'
        unit_of_measurement: '%'
  # indoor temperature sensor
  - platform: mqtt
    name: weather_indoor_temperature
    state_topic: zigbee2mqtt/weather_indoor
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "°C"
    icon: mdi:temperature-celsius
    value_template: "{{ value_json.temperature }}"
    json_attributes:
      - battery
      - voltage
      - linkquality
  - platform: mqtt
    name: weather_indoor_humidity
    state_topic: zigbee2mqtt/weather_indoor
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "%"
    icon: mdi:water-percent
    value_template: "{{ value_json.humidity }}"
  - platform: mqtt
    name: weather_indoor_pressure
    state_topic: zigbee2mqtt/weather_indoor
    availability_topic: zigbee2mqtt/bridge/state
    unit_of_measurement: "Pa"
    icon: mdi:speedometer
    value_template: "{{ value_json.pressure }}"
  - platform: template
    sensors:
      weather_indoor_battery:
        value_template: '{{ states.sensor.weather_indoor_temperature.attributes.battery }}'
        unit_of_measurement: '%'

  # xiaomi cube
  - platform: mqtt
    name: xiaomi_cube
    state_topic: zigbee2mqtt/xiaomi_cube
    availability_topic: zigbee2mqtt/bridge/state
    icon: mdi:gesture-double-tap
    value_template: "{{ value_json.action }}"
    json_attributes:
      - battery
      - voltage
      - linkquality
      - angle
      - side
      - from_side
      - to_side
      - brightness
      - angle_x_absolute
      - angle_y_absolute
      - angle_z
      - angle_y
      - angle_x
      - unknown_data
    force_update: true
  - platform: template
    sensors:
      xiaomi_cube_battery:
        value_template: '{{ states.sensor.xiaomi_cube.attributes.battery }}'
        unit_of_measurement: '%'

  # flora sensor 1
  - platform: mqtt
    name: flora_sensor_1_temperature
    state_topic: flora/C4:7C:8D:67:0F:60/temperature
    unit_of_measurement: "°C"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_1_moisture
    state_topic: flora/C4:7C:8D:67:0F:60/moisture
    unit_of_measurement: "%"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_1_light
    state_topic: flora/C4:7C:8D:67:0F:60/light
    unit_of_measurement: "lux"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_1_conductivity
    state_topic: flora/C4:7C:8D:67:0F:60/conductivity
    unit_of_measurement: "µS/cm"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_1_battery
    state_topic: flora/C4:7C:8D:67:0F:60/battery
    unit_of_measurement: "%"
    value_template: "{{ value_json }}"

  # flora sensor 2
  - platform: mqtt
    name: flora_sensor_2_temperature
    state_topic: flora/C4:7C:8D:67:0F:0D/temperature
    unit_of_measurement: "°C"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_2_moisture
    state_topic: flora/C4:7C:8D:67:0F:0D/moisture
    unit_of_measurement: "%"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_2_light
    state_topic: flora/C4:7C:8D:67:0F:0D/light
    unit_of_measurement: "lux"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_2_conductivity
    state_topic: flora/C4:7C:8D:67:0F:0D/conductivity
    unit_of_measurement: "µS/cm"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_2_battery
    state_topic: flora/C4:7C:8D:67:0F:0D/battery
    unit_of_measurement: "%"
    value_template: "{{ value_json }}"

  # flora sensor 3
  - platform: mqtt
    name: flora_sensor_3_temperature
    state_topic: flora/C4:7C:8D:67:0D:BC/temperature
    unit_of_measurement: "°C"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_3_moisture
    state_topic: flora/C4:7C:8D:67:0D:BC/moisture
    unit_of_measurement: "%"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_3_light
    state_topic: flora/C4:7C:8D:67:0D:BC/light
    unit_of_measurement: "lux"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_3_conductivity
    state_topic: flora/C4:7C:8D:67:0D:BC/conductivity
    unit_of_measurement: "µS/cm"
    value_template: "{{ value_json }}"
  - platform: mqtt
    name: flora_sensor_3_battery
    state_topic: flora/C4:7C:8D:67:0D:BC/battery
    unit_of_measurement: "%"
    value_template: "{{ value_json }}"

plant:
  plant_one:
    sensors:
      moisture: sensor.flora_sensor_1_moisture
      battery: sensor.flora_sensor_1_battery
      temperature: sensor.flora_sensor_1_temperature
      conductivity: sensor.flora_sensor_1_conductivity
      brightness: sensor.flora_sensor_1_light
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 500
    min_temperature: 15

  plant_two:
    sensors:
      moisture: sensor.flora_sensor_2_moisture
      battery: sensor.flora_sensor_2_battery
      temperature: sensor.flora_sensor_2_temperature
      conductivity: sensor.flora_sensor_2_conductivity
      brightness: sensor.flora_sensor_2_light
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 500
    min_temperature: 15

  plant_three:
    sensors:
      moisture: sensor.flora_sensor_3_moisture
      battery: sensor.flora_sensor_3_battery
      temperature: sensor.flora_sensor_3_temperature
      conductivity: sensor.flora_sensor_3_conductivity
      brightness: sensor.flora_sensor_3_light
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 500
    min_temperature: 15
