sensor:
  - platform: syncthru
    resource: !secret syncthru_resource
    name: samsung_printer
    scan_interval: 1800
    monitored_conditions:
    - toner_black
    - toner_cyan
    - toner_magenta
    - toner_yellow
    - tray_1
    - output_tray_0
