sensor:
  - platform: syncthru
    resource: !secret syncthru_resource
    name: samsung_printer
    scan_interval: 1800
    monitored_conditions:
    - toner_black
    - toner_cyan
    - toner_magenta
    - toner_yellow
    - tray_1
    - output_tray_0

group:
  samsung_printer:
    entities:
    - sensor.samsung_printer_output_tray_0
    - sensor.samsung_printer_toner_black
    - sensor.samsung_printer_toner_cyan
    - sensor.samsung_printer_toner_magenta
    - sensor.samsung_printer_toner_yellow
    - sensor.samsung_printer_tray_1
