sensor:
  - platform: synologydsm
    host: !secret synology_host
    username: !secret synology_username
    password: !secret synology_password
    scan_interval: 1800
    monitored_conditions:
    - volume_size_total
    - volume_percentage_used
    - disk_name
    - disk_smart_status
    - memory_real_usage

group:
  synology:
    entities:
    - sensor.memory_usage_real
    - sensor.name_sda
    - sensor.status_smart_sda
    - sensor.name_sdb
    - sensor.status_smart_sdb
    - sensor.total_size_volume_1
    - sensor.volume_used_volume_1
    - sensor.total_size_volume_2
    - sensor.volume_used_volume_2
