binary_sensor:
  - platform: template
    sensors:
      amazon_echo_bedroom_online:
        value_template: >
          {{ is_state('device_tracker.amazon_echo_schlafzimmer', 'home')}}
      amazon_echo_living_room_online:
        value_template: >
          {{ is_state('device_tracker.amazon_echo_wohnzimmer', 'home')}}
      google_home_office_online:
        value_template: >
          {{ is_state('device_tracker.google_home_mini_eva', 'home')}}
      google_home_guestroom_online:
        value_template: >
          {{ is_state('device_tracker.google_home_mini_gastezimmer', 'home')}}
      google_home_shower_online:
        value_template: >
          {{ is_state('device_tracker.google_home_mini_jens_dusche', 'home')}}
      google_home_living_room_online:
        value_template: >
          {{ is_state('device_tracker.google_home_wohnzimmer', 'home')}}
      firetv_bedroom_online:
        value_template: >
          {{ is_state('device_tracker.firetv_schlafzimmer', 'home')}}
      firetv_living_room_online:
        value_template: >
          {{ is_state('device_tracker.firetv_wohnzimmer', 'home')}}
      sonos_left_online:
        value_template: >
          {{ is_state('device_tracker.sonos_links', 'home')}}
      sonos_playbase_online:
        value_template: >
          {{ is_state('device_tracker.sonos_playbase', 'home')}}
      sonos_right_online:
        value_template: >
          {{ is_state('device_tracker.sonos_rechts', 'home')}}
      sonos_sub_online:
        value_template: >
          {{ is_state('device_tracker.sonos_sub', 'home')}}
      power_plug_dryer_online:
        value_template: >
          {{ is_state('device_tracker.steckdose_trockner', 'home')}}
      power_plug_washer_human_online:
        value_template: >
          {{ is_state('device_tracker.steckdose_waschmaschine_mensch', 'home')}}
      power_plug_washer_animal_online:
        value_template: >
          {{ is_state('device_tracker.steckdose_waschmaschine_tier', 'home')}}

      ship_online:
        value_template: >
          {{ is_state('device_tracker.ship', 'home')}}
      dss_ip_online:
        value_template: >
          {{ is_state('device_tracker.dss_ip', 'home')}}
      dss_gateway_online:
        value_template: >
          {{ is_state('device_tracker.dss_gateway', 'home')}}
      synology_online:
        value_template: >
          {{ is_state('device_tracker.synology', 'home')}}
      samsung_printer_online:
        value_template: >
          {{ is_state('device_tracker.samsung_drucker', 'home')}}
      philips_hue_controller_online:
        value_template: >
          {{ is_state('device_tracker.philips_hue_hub', 'home')}}
      harmony_hub_online:
        value_template: >
          {{ is_state('device_tracker.harmony_hub', 'home')}}

group:
  automation_devices:
    entities:
    - binary_sensor.amazon_echo_bedroom_online
    - binary_sensor.amazon_echo_living_room_online
    - binary_sensor.google_home_office_online
    - binary_sensor.google_home_guestroom_online
    - binary_sensor.google_home_shower_online
    - binary_sensor.google_home_living_room_online
    - binary_sensor.firetv_bedroom_online
    - binary_sensor.firetv_living_room_online
    - binary_sensor.sonos_playbase_online
    - binary_sensor.sonos_left_online
    - binary_sensor.sonos_right_online
    - binary_sensor.sonos_sub_online
    - binary_sensor.power_plug_dryer_online
    - binary_sensor.power_plug_washer_human_online
    - binary_sensor.power_plug_washer_animal_online
  infrastructure_devices:
    entities:
    - binary_sensor.ship_online
    - binary_sensor.dss_ip_online
    - binary_sensor.dss_gateway_online
    - binary_sensor.synology_online
    - binary_sensor.samsung_printer_online
    - binary_sensor.philips_hue_controller_online
    - binary_sensor.harmony_hub_online
