sensor:
  - platform: google_travel_time
    api_key: !secret google_maps_key
    name: travel_time_jens
    origin: zone.home
    destination: zone.work_jens
    mode: driving
    scan_interval: 600

  - platform: google_travel_time
    api_key: !secret google_maps_key
    name: travel_time_eva
    origin: zone.home
    destination: zone.work_eva
    mode: driving
    scan_interval: 600
