sensor:
  - platform: waze_travel_time
    name: travel_time_jens
    origin: zone.home
    destination: zone.work_jens
    region: 'EU'
  - platform: waze_travel_time
    name: travel_time_eva
    origin: zone.home
    destination: zone.work_eva
    region: 'EU'
