# unifi device tracker is set up via integrations - config not required anymore

sensor:
  - platform: unifigateway
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    site_id: !secret unifi_siteid
    verify_ssl: False
    monitored_conditions:
      - vpn
      - www
      - wan
      - wlan
      - alerts
      - firmware
