switch:
  # TP-Link HS110 power plug
  - platform: tplink
    name: power_plug_washer_animal
    host: !secret tplink_power_plug_washer_animal

input_select:
  # status selector
  washer_animal_status:
    initial: Aus
    icon: mdi:power
    options:
    - "Aus"
    - "Aktiv"
    - "Fertig"

sensor:
  - platform: template
    # define the triggers that update this template sensor
    entity_id:
    - switch.power_plug_washer_animal
    sensors:
      # define current power attribute as seperate sensor
      washer_animal_current_power_usage:
        value_template: '{{ states.switch.power_plug_washer_animal.attributes.current_power_w }}'
        unit_of_measurement: 'W'
      # define input select read only sensor
      washer_animal_status_text:
        value_template: '{{ states.input_select.washer_animal_status.state }}'

  # define history sensor for mean power usage of last 5 minutes
  - platform: statistics
    name: washer_animal_consumption_last_5_mins
    entity_id: sensor.washer_animal_current_power_usage
    max_age:
      minutes: 5

# package group
group:
  washer_animal:
    entities:
    - switch.power_plug_washer_animal
    - sensor.washer_animal_status_text
    - sensor.washer_animal_current_power_usage
    - sensor.washer_animal_consumption_last_5_mins_mean
