blueprint:
  name: Ansage
  domain: script

mode: restart

sequence:
  - service: scene.create
    data:
      scene_id: "media_player_{{ media_player }}_snapshot"
      snapshot_entities:
      - "{{ media_player }}"
  - service: media_player.volume_set
    data:
      volume_level: "{{ volume / 100 }}"
    target:
      entity_id: "{{ media_player }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: notify.alexa_media
    data:
      message: "{{ message }}"
      target:
        - "{{ media_player }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
    alias: 10s warten
  - service: scene.turn_on
    target:
      entity_id: "media_player_{{ media_player }}_snapshot"
