[http]
  [http.middlewares]
    [http.middlewares.https-chain]
      [http.middlewares.https-chain.chain]
        middlewares = ["headers-sts", "header-frame", "compress"]

    [http.middlewares.headers-sts]
      [http.middlewares.headers-sts.headers]
        stsSeconds = 315360000
        stsIncludeSubdomains = true
        stsPreload = true
        forceSTSHeader = true

    [http.middlewares.header-frame]
    #   [http.middlewares.header-frame.headers]
    #     contentSecurityPolicy = "frame-ancestors 'self' $MY_DOMAIN"

    [http.middlewares.compress]
      [http.middlewares.compress.compress]
