# gosund sp111 v1.1
# 23

substitutions:
  id: sp111_plug_spare_23
  update_throttle: 30s

  name_a: SP111 23

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp111.yaml
  template_a: !include common/template_output_a_switch.yaml
