# gosund sp112 v3.4
# 03

substitutions:
  id: plug_sp112_spare_03
  update_throttle: 30s

  name_a: sp112_spare_03
  name_b: sp112_spare_03 USB

  cf1_pin: GPIO04
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO14
  actor_pin_usb: GPIO13

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp112_v34.yaml
  template_a: !include common/template_output_a_switch.yaml
  template_b: !include common/template_output_b_switch.yaml
