# gosund sp112 v2.8
# 04

substitutions:
  id: plug_sp112_spare_04
  update_throttle: 30s

  name_a: SP112 04
  name_b: SP112 04 USB

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp112_v28.yaml
