# shelly 2.5
# 10
# ex bathroom - crashed all the time

substitutions:
  id: shelly25_spare_19
  update_throttle: 30s

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
