<<: !include .defaults.yaml

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

# binary_sensor:
#   # device status sensor
#   - platform: status
#     name: "${name} status"
#   # binary sensor for the button press
#   - platform: gpio
#     name: "${name} sensor"
#     pin:
#       number: GPIO03
#       # inverted: true
#       # mode: INPUT_PULLUP
#     on_press:
#       - switch.turn_off: "${name}_actor_all"
#     on_double_click:
#       - switch.turn_on: "${name}_actor_all"

switch:
  # switch to restart the plug
  - platform: restart
    name: "${name} restart"
  # switch to toggle the relay of plug 1
  - platform: gpio
    id: "${name}_actor_1"
    name: "${name} switch 1"
    pin: GPIO05
  # switch to toggle the relay of plug 2
  - platform: gpio
    id: "${name}_actor_2"
    name: "${name} switch 2"
    pin: GPIO04
  # switch to toggle the relay of plug 3
  - platform: gpio
    id: "${name}_actor_3"
    name: "${name} switch 3"
    pin: GPIO12
  # switch to toggle the relay of plug 4
  - platform: gpio
    id: "${name}_actor_4"
    name: "${name} switch 4"
    pin: GPIO13
  # switch to toggle the relay of usb ports
  - platform: gpio
    id: "${name}_actor_usb"
    name: "${name} switch USB"
    pin: GPIO14
  # template switch to turn off all outlets (except for usb) at once
  - platform: template
    id: "${name}_actor_all"
    name: "${name} switch all"
    turn_on_action:
      - switch.turn_on: "${name}_actor_1"
      - switch.turn_on: "${name}_actor_2"
      - switch.turn_on: "${name}_actor_3"
      - switch.turn_on: "${name}_actor_4"
    turn_off_action:
      - switch.turn_off: "${name}_actor_1"
      - switch.turn_off: "${name}_actor_2"
      - switch.turn_off: "${name}_actor_3"
      - switch.turn_off: "${name}_actor_4"

# status_led:
#   # uses the led as a status indicator
#   pin:
#     number: GPIO01
#     inverted: true
