# wifi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

# enable logging
logger:

# enable Home Assistant API
api:
  password: !secret esphome_api_password

# enable over-the-air updates
ota:
  password: !secret esphome_ota_password

# enable Web server
web_server:
  port: 80

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# text sensors with general information
text_sensor:
  - platform: version
    name: "${name}_version"
  - platform: wifi_info
    ip_address:
      name: "${name}_ip"
    ssid:
      name: "${name}_ssid"
    bssid:
      name: "${name}_bssid"

sensor:
  # uptime sensor
  - platform: uptime
    name: "${name}_uptime"
    unit_of_measurement: seconds
    update_interval: 10min
  # wifi signal sensor
  - platform: wifi_signal
    name: "${name}_wifi_signal"
    filters:
      - or:
        - heartbeat: 1h
        - delta: 3

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name} status"
