<<: !include .defaults.yaml

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

switch:
  # switch to restart the device
  - platform: restart
    name: "${name} restart"

light:
  # light combining all three color channels
  - platform: rgb
    name: "${name} light"
    red: red_output
    green: green_output
    blue: blue_output
    restore_mode: RESTORE_DEFAULT_OFF

output:
  # red color channel
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO5
  # green color channel
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  # blue color channel
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO13
