# example

substitutions:
  name: esphome_switch_shelly1_example

<<: !include .shelly1.yaml

light:
  - platform: binary
    id: "${name}_light"
    name: "${name} light"
    output: "${name}_actor"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name} status"
  # binary sensor for the button press
  - platform: gpio
    name: "${name} sensor"
    pin:
      number: GPIO5
      inverted: false
    on_press:
      - light.toggle: "${name}_light"
