<<: !include .shelly25.yaml

substitutions:
  name: shelly25_example
  friendly_name: Shelly 2.5 example
  update_throttle: 30s

# define our first actor
light:
  - platform: binary
    id: "${name}_light"
    name: "${friendly_name} light"
    output: "${name}_actor_a"

# define our second actor
fan:
  - platform: binary
    id: "${name}_fan"
    name: "${friendly_name} fan"
    output: "${name}_actor_b"

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name}_status"
  # binary sensor for the button A press
  - platform: gpio
    name: "${friendly_name} sensor A"
    pin:
      number: GPIO13
      inverted: false
    # should toggle the device defined by actor A
    on_press:
      then:
        - light.toggle: "${name}_light"
  # binary sensor for the button B press
  - platform: gpio
    name: "${friendly_name} sensor B"
    pin:
      number: GPIO5
      inverted: false
    # should toggle the device defined by actor B
    on_press:
      then:
        - fan.toggle: "${name}_fan"

# overheat protection, shut actors off above 70 celsius
interval:
  - interval: 100ms
    then:
      if:
        condition:
          and:
            - sensor.in_range:
                id: "${name}_temperature"
                above: 70.0
        then:
          - light.turn_off: "${name}_light"
          - fan.turn_off: "${name}_fan"
