# guestroom - shutter

<<: !include .shelly25_cover.yaml

substitutions:
  name: esphome_switch_shelly25_38
  update_throttle: 10s

  # how long to continue when the endposition has been reached?
  stop_delay: 2sec

  # cover power consumption thresholds
  cover_moving: "100.0"  # everything above this value means the motor is moving
  cover_stopping: "30.0"  # everything above this value but below cover_moving means the motor is reaching the end position
  cover_stopped: "5.0"  # everything below that value means the motor has stopped

  # control direction for each switch
  switch_a: "up"
  switch_b: "down"

  # how long does a full run take?
  close_duration: 23sec  # from fully open to fully closed
  open_duration: 23sec  # from fully closed to fully open
  max_duration: 30sec  # always stop after this time
