substitutions:
  name: esphome_switch_shelly25_example

<<: !include .shelly25.yaml

# define our first actor
light:
  - platform: binary
    id: "${name}_light"
    name: "${name} light"
    output: "${name}_actor_a"

fan:
  - platform: binary
    id: "${name}_fan"
    name: "${name} fan"
    output: "${name}_actor_b"

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name}_status"
  # binary sensor for the button A press
  - platform: gpio
    name: "${name} sensor A"
    pin:
      number: GPIO13
      inverted: false
    # should toggle the device defined by actor A
    on_press:
      then:
        - light.toggle: "${name}_light"
  # binary sensor for the button B press
  - platform: gpio
    name: "${name} sensor B"
    pin:
      number: GPIO5
      inverted: false
    # should toggle the device defined by actor B
    on_press:
      then:
        - fan.toggle: "${name}_fan"

# overheat protection, shut actors off above 60 celsius
interval:
  - interval: 100ms
    then:
      if:
        condition:
          and:
            - sensor.in_range:
                id: "${name}_temperature"
                above: 60.0
        then:
          - light.turn_off: "${name}_light"
          - fan.turn_off: "${name}_fan"
