<<: !include .defaults.yaml

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name} status"
  # binary sensor for the button press
  - platform: gpio
    name: "${name} sensor"
    pin:
      number: GPIO13
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: "${name}_actor"

switch:
  # switch to restart the plug
  - platform: restart
    name: "${name} restart"
  # switch to toggle the relay
  - platform: gpio
    id: "${name}_actor"
    name: "${name} switch"
    pin: GPIO05
    restore_mode: ${restore_mode}

status_led:
  # uses the red led as a status indicator
  pin:
    number: GPIO04
    inverted: true
