<<: !include .defaults.yaml

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name} status"
  # binary sensor for the button 1 press
  - platform: gpio
    id: "${name}_sensor_1"
    name: "${name} sensor 1"
    pin:
      number: GPIO12
  # binary sensor for the button 2 press
  - platform: gpio
    id: "${name}_sensor_2"
    name: "${name} sensor 2"
    pin:
      number: GPIO14
  # binary sensor for the button 3 press
  - platform: gpio
    id: "${name}_sensor_3"
    name: "${name} sensor 3"
    pin:
      number: GPIO13

switch:
  # switch to restart the device
  - platform: restart
    name: "${name} restart"
