<<: !include .defaults.yaml

# this setup uses momentary switches!!!
#
# SW1 must be connected to the upwards switch
# SW2 must be connected to the downwards switch
# actor direction can be changed by setting output_1 and output_2 to "up"/"down"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  on_shutdown:
    then:
      # store the current cover position
      - globals.set:
          id: cover_position
          value: id(${name}_cover).position
  on_boot:
    then:
      # restore the cover position
      - lambda: id(${name}_cover).publish_state(id(cover_position));
      # restore upper endstop status based on cover position
      - if:
          condition:
            lambda: 'return id(cover_position) == 100;'
          then:
            - binary_sensor.template.publish:
                id: "${name}_endstop_up"
                state: ON
          else:
            - binary_sensor.template.publish:
                id: "${name}_endstop_up"
                state: OFF
      # restore lower endstop status based on cover position
      - if:
          condition:
            lambda: 'return id(cover_position) == 0;'
          then:
            - binary_sensor.template.publish:
                id: "${name}_endstop_down"
                state: ON
          else:
            - binary_sensor.template.publish:
                id: "${name}_endstop_down"
                state: OFF

i2c:
  sda: GPIO12
  scl: GPIO14
  scan: False

globals:
  # used to store the state of the cover while rebooting the device
  - id: cover_position
    type: int
    restore_value: yes

sensor:
  # uptime sensor
  - platform: uptime
    name: "${name}_uptime"
    unit_of_measurement: seconds
    update_interval: 10min
  # wifi signal sensor
  - platform: wifi_signal
    name: "${name} wifi signal"
    filters:
      - or:
        - heartbeat: 1h
        - delta: 3

  # power measurement
  - platform: ade7953
    address: 0x38
    update_interval: 1s
    voltage:
      name: "${name} voltage"
      filters:
        - throttle: ${update_throttle}
    current_a:
      name: "${name} current ${output_1}"
      filters:
        - lambda: if (x < 0.1) return 0; else return (x);
        - or:
          - throttle: ${update_throttle}
          - delta: 0.03
    current_b:
      name: "${name} current ${output_2}"
      filters:
        - lambda: if (x < 0.1) return 0; else return (x);
        - or:
          - throttle: ${update_throttle}
          - delta: 0.03
    active_power_a:
      id: "${name}_power_usage_${output_1}"
      name: "${name} power ${output_1}"
      unit_of_measurement: W
      icon: mdi:flash-circle
      accuracy_decimals: 0
      filters:
        - lambda: if (x < 1) return 0; else return (x);
        - or:
          - throttle: ${update_throttle}
          - delta: 1
      on_value:
        then:
          # consumption is higher than the moving threshold
          # mark motor as not in slowdown
          - if:
              condition:
                lambda: 'return id(${name}_power_usage_${output_1}).state > ${cover_moving};'
              then:
                - logger.log:
                    format: "Cover is moving ${output_1}"
                    level: INFO
                - binary_sensor.template.publish:
                    id: "${name}_slowdown_${output_1}"
                    state: OFF
          # consumption is higher than the stopping threshold but less than the moving threshold
          # mark motor as slowing down
          - if:
              condition:
                - lambda: 'return id(${name}_power_usage_${output_1}).state > ${cover_stopping};'
                - lambda: 'return id(${name}_power_usage_${output_1}).state < ${cover_moving};'
              then:
                - logger.log:
                    format: "Cover is close to the ${output_1}wards endposition and slowing down"
                    level: INFO
                - binary_sensor.template.publish:
                    id: "${name}_slowdown_${output_1}"
                    state: ON
          # consumption stopped after being on slowdown
          # mark motor as fully stopped on end position
          - if:
              condition:
                - lambda: 'return id(${name}_power_usage_${output_1}).state < ${cover_stopped};'
                - binary_sensor.is_on: "${name}_moving"
                - binary_sensor.is_on: "${name}_slowdown_${output_1}"
              then:
                - logger.log:
                    format: "Cover has reached the ${output_1}wards endposition and stopped"
                    level: INFO
                - binary_sensor.template.publish:
                    id: "${name}_endstop_${output_1}"
                    state: ON
                - binary_sensor.template.publish:
                    id: "${name}_slowdown_${output_1}"
                    state: OFF
    active_power_b:
      id: "${name}_power_usage_${output_2}"
      name: "${name} power ${output_2}"
      unit_of_measurement: W
      icon: mdi:flash-circle
      accuracy_decimals: 0
      filters:
        - multiply: -1
        - lambda: if (x < 1) return 0; else return (x);
        - or:
          - throttle: ${update_throttle}
          - delta: 1
      on_value:
        then:
          # consumption is higher than the moving threshold
          # mark motor as not in slowdown
          - if:
              condition:
                lambda: 'return id(${name}_power_usage_${output_2}).state > ${cover_moving};'
              then:
                - logger.log:
                    format: "Cover is moving ${output_2}"
                    level: INFO
                - binary_sensor.template.publish:
                    id: "${name}_slowdown_${output_2}"
                    state: OFF
          # consumption is higher than the stopping threshold but less than the moving threshold
          # mark motor as slowing down
          - if:
              condition:
                - lambda: 'return id(${name}_power_usage_${output_2}).state > ${cover_stopping};'
                - lambda: 'return id(${name}_power_usage_${output_2}).state < ${cover_moving};'
              then:
                - logger.log:
                    format: "Cover is close to the ${output_2}wards endposition and slowing down"
                    level: INFO
                - binary_sensor.template.publish:
                    id: "${name}_slowdown_${output_2}"
                    state: ON
          # consumption stopped after being on slowdown
          # mark motor as fully stopped on end position
          - if:
              condition:
                - lambda: 'return id(${name}_power_usage_${output_2}).state < ${cover_stopped};'
                - binary_sensor.is_on: "${name}_moving"
                - binary_sensor.is_on: "${name}_slowdown_${output_2}"
              then:
                - logger.log:
                    format: "Cover has reached the ${output_2}wards endposition and stopped"
                    level: INFO
                - binary_sensor.template.publish:
                    id: "${name}_endstop_${output_2}"
                    state: ON
                - binary_sensor.template.publish:
                    id: "${name}_slowdown_${output_2}"
                    state: OFF

  # device temperature
  - platform: ntc
    sensor: "${name}_resistance_reading"
    id: "${name}_temperature"
    name: "${name} temperature"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: "${name}_resistance_reading"
    sensor: "${name}_analog_reading"
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: "${name}_analog_reading"
    pin: A0

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name}_status"
  # binary sensor for the upwards button press
  - platform: gpio
    name: "${name} sensor up"
    pin:
      number: GPIO13
      inverted: false
    on_press:
      # if the motor is moving, every press should just stop it
      - if:
          condition:
            binary_sensor.is_on: "${name}_moving"
          then:
            cover.stop: "${name}_cover"
          else:
            cover.open: "${name}_cover"
  # binary sensor for the downwards button press
  - platform: gpio
    name: "${name} sensor down"
    pin:
      number: GPIO5
      inverted: false
    on_press:
        # if the motor is moving, every press should just stop it
        - if:
            condition:
              binary_sensor.is_on: "${name}_moving"
            then:
              cover.stop: "${name}_cover"
            else:
              cover.close: "${name}_cover"
  # endstop sensors
  - platform: template
    id: "${name}_endstop_up"
    name: "${name} up endstop"
  - platform: template
    id: "${name}_slowdown_up"
    name: "${name} up slowdown"
  - platform: template
    id: "${name}_endstop_down"
    name: "${name} down endstop"
  - platform: template
    id: "${name}_slowdown_down"
    name: "${name} down slowdown"
  # cover is moving
  - platform: template
    id: "${name}_moving"
    name: "${name} is moving"

switch:
  - platform: restart
    name: ${name} Restart
  # actual switch powering the motor, direction is defined by setting output_1 to "up" or "down"
  - platform: gpio
    id: "${name}_cover_${output_1}"
    name: "${name} cover ${output_1}"
    pin:
      number: GPIO15
    # prevent both switches from being turned on at the same time
    interlock: &interlock ["${name}_cover_up", "${name}_cover_down"]
    interlock_wait_time: 500ms
    # set motor moving when not yet at the upper endstop, also remove eventual lower endstop flag as we're moving up
    on_turn_on:
      - if:
          condition:
            binary_sensor.is_off: "${name}_endstop_${output_1}"
          then:
            - binary_sensor.template.publish:
                id: "${name}_moving"
                state: ON
            - binary_sensor.template.publish:
                id: "${name}_endstop_${output_2}"
                state: OFF
    on_turn_off:
      - binary_sensor.template.publish:
          id: "${name}_moving"
          state: OFF
  # actual switch powering the motor, direction is defined by setting output_2 to "up" or "down"
  - platform: gpio
    id: "${name}_cover_${output_2}"
    name: "${name} cover ${output_2}"
    pin:
      number: GPIO4
    # prevent both switches from being turned on at the same time
    interlock: *interlock
    interlock_wait_time: 500ms
    # set motor moving when not yet at the lower endstop, also remove eventual upper endstop flag as we're moving down
    on_turn_on:
      - if:
          condition:
            binary_sensor.is_off: "${name}_endstop_${output_2}"
          then:
            - binary_sensor.template.publish:
                id: "${name}_moving"
                state: ON
            - binary_sensor.template.publish:
                id: "${name}_endstop_${output_1}"
                state: OFF
    on_turn_off:
      - binary_sensor.template.publish:
          id: "${name}_moving"
          state: OFF

cover:
  - platform: endstop
    name: "${name} cover"
    id: "${name}_cover"
    max_duration: ${max_duration}

    open_action:
      - switch.turn_on: "${name}_cover_up"
    open_duration: ${open_duration}
    open_endstop: "${name}_endstop_up"

    close_action:
      - switch.turn_on: "${name}_cover_down"
    close_duration: ${close_duration}
    close_endstop: "${name}_endstop_down"

    stop_action:
      - switch.turn_off: "${name}_cover_up"
      - switch.turn_off: "${name}_cover_down"
