<<: !include _defaults.yaml

# see https://templates.blakadder.com/aofo_4AC4USB.html

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

# text sensors with general information
text_sensor:
  - platform: version
    name: "${name}_version"
  - platform: wifi_info
    ip_address:
      name: "${name}_ip"
    ssid:
      name: "${name}_ssid"
    bssid:
      name: "${name}_bssid"

sensor:
  # uptime sensor
  - platform: uptime
    name: "${name}_uptime"
  # wifi signal sensor
  - platform: wifi_signal
    name: "${name}_wifi_signal"
    update_interval: 10s

switch:
  # switch to restart the plug
  - platform: restart
    name: "${name}_restart"
  # switch to toggle the relay of plug 1
  - platform: gpio
    id: "${name}_relay_1"
    name: "${name}_switch_1"
    pin: GPIO05
  # switch to toggle the relay of plug 2
  - platform: gpio
    id: "${name}_relay_2"
    name: "${name}_switch_2"
    pin: GPIO04
  # switch to toggle the relay of plug 3
  - platform: gpio
    id: "${name}_relay_3"
    name: "${name}_switch_3"
    pin: GPIO12
  # switch to toggle the relay of plug 4
  - platform: gpio
    id: "${name}_relay_4"
    name: "${name}_switch_4"
    pin: GPIO13
  # switch to toggle the relay of usb ports
  - platform: gpio
    id: "${name}_relay_usb"
    name: "${name}_switch_usb"
    pin: GPIO14
    
