# wifi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# enable logging
logger:

# enable Home Assistant API
api:
  password: !secret esphome_api_password

# enable over-the-air updates
ota:
  password: !secret esphome_ota_password

# enable Web server
web_server:
  port: 80

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
