<<: !include _defaults.yaml

# see https://templates.blakadder.com/SWA11.html

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285
  # esp8266_restore_from_flash: true

# text sensors with general information
text_sensor:
  - platform: version
    name: "${name}_version"
  - platform: wifi_info
    ip_address:
      name: "${name}_ip"
    ssid:
      name: "${name}_ssid"
    bssid:
      name: "${name}_bssid"

sensor:
  # uptime sensor
  - platform: uptime
    name: "${name}_uptime"
  # wifi signal sensor
  - platform: wifi_signal
    name: "${name}_wifi_signal"
    update_interval: 10s

binary_sensor:
  # binary sensor for the button press
  - platform: gpio
    name: "${name}_button"
    pin:
      number: GPIO13
      inverted: true
    on_press:
      - switch.toggle: "${name}_relay"

switch:
  # switch to restart the plug
  - platform: restart
    name: "${name}_restart"
  # switch to toggle the relay
  - platform: gpio
    id: "${name}_relay"
    name: "${name}_switch"
    pin: GPIO05
    # restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - light.turn_on: "${name}_led"
    on_turn_off:
      - light.turn_off: "${name}_led"

output:
  # relay state led
  - platform: esp8266_pwm
    id: "${name}_state_led"
    pin:
      number: GPIO04
      inverted: true

light:
  # relay state light
  - platform: monochromatic
    output: "${name}_state_led"
    id: "${name}_led"
