<<: !include _defaults.yaml

# see https://templates.blakadder.com/SWA11.html
# translation https://tasmota.github.io/docs/Components/

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

binary_sensor:
  # binary sensor for the button press
  - platform: gpio
    name: "${name}_button"
    pin:
      number: GPIO13
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: "${name}_relay"

switch:
  # switch to restart the plug
  - platform: restart
    name: "${name}_restart"
  # switch to toggle the relay
  - platform: gpio
    id: "${name}_relay"
    name: "${name}_switch"
    pin: GPIO05

status_led:
  # uses the red led as a status indicator
  pin:
    number: GPIO04
    inverted: true
