# livingroom - tv, sonos, phone, multimedia

substitutions:
  id: esphome_aofo_4ac4usb_01
  update_throttle: 30s

  name_a: Fernseher Wohnzimmer
  restore_mode_a: RESTORE_DEFAULT_OFF 
  name_b: Sonos Sub
  restore_mode_b: RESTORE_DEFAULT_OFF 
  name_c: Telefon Wohnzimmer
  restore_mode_c: RESTORE_DEFAULT_OFF 
  name_d: Sonos Playbase
  restore_mode_d: RESTORE_DEFAULT_OFF 
  name_e: Steckdosenleiste Wohnzimmmer USB
  restore_mode_e: RESTORE_DEFAULT_OFF 

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_aofo_4ac4usb.yaml
