# magichome
# 01

substitutions:
  id: light_shower_mirror
  friendly_name: Spiegellicht Dusche
  update_throttle: 30s

  name_a: Spiegellicht Dusche

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_magichome.yaml
