# livingroom - ceiling

<<: !include .defaults.yaml

esphome:
  name: esphome_miflora
  platform: ESP32
  board: nodemcu-32s

esp32_ble_tracker:

sensor:
  # uptime sensor
  - platform: uptime
    name: "${name}_uptime"
  # wifi signal sensor
  - platform: wifi_signal
    name: "${name}_wifi_signal"
    update_interval: 30s

  # gruenlilie neben orchideen
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:67:0F:60
    temperature:
      name: "Xiaomi MiFlora 1 Temperature"
    moisture:
      name: "Xiaomi MiFlora 1 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 1 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 1 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 1 Battery Level"

  # einblatt auf bar
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:67:0F:0D
    temperature:
      name: "Xiaomi MiFlora 2 Temperature"
    moisture:
      name: "Xiaomi MiFlora 2 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 2 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 2 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 2 Battery Level"

  # benjamini neben tv
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:67:0D:BC
    temperature:
      name: "Xiaomi MiFlora 3 Temperature"
    moisture:
      name: "Xiaomi MiFlora 3 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 3 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 3 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 3 Battery Level"

  # aloe vera auf bar
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:D5:A3
    temperature:
      name: "Xiaomi MiFlora 4 Temperature"
    moisture:
      name: "Xiaomi MiFlora 4 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 4 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 4 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 4 Battery Level"

  # flamingoblume auf esstisch
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:F2:25
    temperature:
      name: "Xiaomi MiFlora 5 Temperature"
    moisture:
      name: "Xiaomi MiFlora 5 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 5 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 5 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 5 Battery Level"

  # gruenlilie neben tv
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:D5:B6
    temperature:
      name: "Xiaomi MiFlora 6 Temperature"
    moisture:
      name: "Xiaomi MiFlora 6 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 6 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 6 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 6 Battery Level"

  # palme wohnzimmer
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:F2:27
    temperature:
      name: "Xiaomi MiFlora 7 Temperature"
    moisture:
      name: "Xiaomi MiFlora 7 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 7 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 7 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 7 Battery Level"

  # rankpflanze gaestezimmer
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:D5:B0
    temperature:
      name: "Xiaomi MiFlora 8 Temperature"
    moisture:
      name: "Xiaomi MiFlora 8 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 8 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 8 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 8 Battery Level"

  # palme gaestezimmer
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:D5:AD
    temperature:
      name: "Xiaomi MiFlora 9 Temperature"
    moisture:
      name: "Xiaomi MiFlora 9 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 9 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 9 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 9 Battery Level"

  # palme gaestezimmer schreibtisch
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:D5:B3
    temperature:
      name: "Xiaomi MiFlora 10 Temperature"
    moisture:
      name: "Xiaomi MiFlora 10 Moisture"
    illuminance:
      name: "Xiaomi MiFlora 10 Illuminance"
    conductivity:
      name: "Xiaomi MiFlora 10 Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora 10 Battery Level"
