# shower - fan
# no switch connected, actor only

substitutions:
  name: esphome_switch_shelly1_02

<<: !include .shelly1.yaml

fan:
  - platform: binary
    id: "${name}_fan"
    name: "${name} fan"
    output: "${name}_actor"
