# shelly 2.5
# 03

substitutions:
  id: light_bedroom_ceiling
  update_throttle: 30s

  name_a: Schlafzimmer Deckenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_output_a_light.yaml
