# shelly 2.5
# 23

<<: !include .shelly25.yaml

substitutions:
  name: shelly25_spare_23
  friendly_name: Shelly 2.5 Spare 23
  update_throttle: 30s

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name}_status"
  # binary sensor for the button A press
  - platform: gpio
    name: "${name} sensor A"
    pin:
      number: GPIO13
      inverted: false
  # binary sensor for the button B press
  - platform: gpio
    name: "${name} sensor B"
    pin:
      number: GPIO5
      inverted: false
