# shelly 1
# 01

substitutions:
  id: light_shower_ceiling
  update_throttle: 30s

  name_a: Dusche Deckenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly1.yaml
  template_a: !include common/template_output_a_light.yaml
