# shelly 2.5
# 14

<<: !include .shelly25.yaml

substitutions:
  name: light_hallway_entrance
  friendly_name: Flurlicht (Eingang)
  update_throttle: 10s

light:
  - platform: binary
    id: "${name}"
    name: "${friendly_name}"
    output: "${name}_actor_a"
    restore_mode: RESTORE_DEFAULT_OFF
