# shelly 1 
# 04

substitutions:
  id: fan_bathroom
  friendly_name: Lüfter Bad
  update_throttle: 30s

  name_a: Lüfter Bad

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly1.yaml
  template_a: !include common/template_fan_binary_a.yaml
