# shelly 2.5
# 04

<<: !include .shelly25_cover_timebased.yaml

substitutions:
  name: cover_dining
  friendly_name: Rolladen Esstisch
  update_throttle: 30s

  # set which direction is connected to which output
  output_1: "down"
  output_2: "up"

  # how long does a full run take?
  close_duration: 33sec  # from fully open to fully closed
  open_duration: 35sec  # from fully closed to fully open
