# shelly 2.5
# 31

<<: !include .shelly25_cover_timebased.yaml

substitutions:
  name: cover_couch
  friendly_name: Rolladen Couch
  update_throttle: 10s

  # set which direction is connected to which output
  output_1: "down"
  output_2: "up"

  # how long does a full run take?
  close_duration: 31sec  # from fully open to fully closed
  open_duration: 33sec  # from fully closed to fully open
