# shelly 2.5
# 16

<<: !include .shelly25.yaml

substitutions:
  name: light_bathroom_mirror
  friendly_name: Bad Spiegellicht
  update_throttle: 30s

light:
  - platform: binary
    id: "${name}"
    name: "${friendly_name}"
    output: "${name}_actor_a"
    restore_mode: RESTORE_DEFAULT_OFF
