# shelly 1 
# 02

substitutions:
  id: fan_shower
  update_throttle: 30s

  name_a: "Lüfter Dusche"

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly1.yaml
  template_a: !include common/template_output_a_fan.yaml
