# shower - ceiling light
# no switch connected, actor only

substitutions:
  name: esphome_switch_shelly1_01

<<: !include .shelly1.yaml

light:
  - platform: binary
    id: "${name}_light"
    name: "${name} light"
    output: "${name}_actor"
    restore_mode: RESTORE_DEFAULT_OFF
