# shelly 2.5
# 16

substitutions:
  id: light_bathroom_mirror
  update_throttle: 30s

  name_a: Bad Spiegellicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_light_binary_a.yaml
