# shelly 2.5
# 24

<<: !include .shelly25.yaml

substitutions:
  name: light_hallway_center
  friendly_name: Flurlicht (Mitte)
  update_throttle: 10s

light:
  - platform: binary
    id: "${name}"
    name: "${friendly_name}"
    output: "${name}_actor_a"
    restore_mode: RESTORE_DEFAULT_OFF
