# shelly 2.5
# 09

substitutions:
  id: switch_garden_valves_2
  update_throttle: 30s

  name_a: Raketen
  name_b: Entnahme

packages:
  wifi: !include common/wifi_basement.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_switch_output_a.yaml
  template_b: !include common/template_switch_output_b.yaml
