# shelly 1 
# 02

substitutions:
  id: fan_shower
  friendly_name: Lüfter Dusche
  update_throttle: 30s

  name_a: Lüfter Dusche

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly1.yaml
  template_a: !include common/template_fan_binary_a.yaml
