# shelly 2.5
# 21

substitutions:
  id: cover_kitchen
  name: Rolladen Küche
  update_throttle: 30s

  # set which direction is connected to which output
  output_1: "down"
  output_2: "up"

  # how long does a full run take?
  close_duration: 19sec  # from fully open to fully closed
  open_duration: 20sec  # from fully closed to fully open

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template: !include common/template_cover_timebased.yaml
