# shelly 2.5
# 03

<<: !include .shelly25.yaml

substitutions:
  name: light_bedroom_ceiling
  friendly_name: Schlafzimmer Deckenlicht
  update_throttle: 30s

light:
  - platform: binary
    id: "${name}"
    name: "${friendly_name}"
    output: "${name}_actor_a"
    restore_mode: RESTORE_DEFAULT_OFF
