# shelly 2.5
# 27

substitutions:
  id: light_kitchen_sink
  update_throttle: 30s

  name_a: Küche Spülenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_output_a_light.yaml
