# shelly 2.5
# 30

substitutions:
  id: light_livingroom_dining
  update_throttle: 30s

  name_a: Wohnzimmer Esstischlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_output_a_light.yaml
