# shelly 2.5
# 29

substitutions:
  id: light_guestroom_ceiling
  update_throttle: 30s

  name_a: Gästezimmer Deckenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_light_binary_a.yaml
