# shelly rgbw2
# 01

substitutions:
  id: light_kitchen_ceiling
  friendly_name: Deckenlicht Küche
  max_power: "0.3"
  cold_white_color_temperature: 6800 K
  warm_white_color_temperature: 2800 K
  default_transition_length: 10ms

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shellyrgbw2.yaml
