# shelly 2.5
# 01

<<: !include .shelly25.yaml

substitutions:
  name: switch_garden_valves_1
  update_throttle: 30s

switch:
  - platform: gpio
    name: "Büsche"
    pin:
      number: GPIO4
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Raketen"
    pin:
      number: GPIO15
    restore_mode: ALWAYS_OFF
