# shelly 2.5
# 22

substitutions:
  id: light_livingroom_ceiling
  update_throttle: 30s

  name_a: Wohnzimmer Deckenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_output_a_light.yaml
