# shelly 1
# 03

substitutions:
  id: light_bathroom_ceiling
  update_throttle: 30s

  name_a: Bad Deckenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly1.yaml
  template_a: !include common/template_light_binary_a.yaml
