# shelly 2.5
# 03

substitutions:
  id: light_bedroom_ceiling
  friendly_name: Deckenlicht Schlafzimmer
  update_throttle: 30s

  name_a: Deckenlicht Schlafzimmer

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_light_binary_a.yaml
