# shelly 2.5
# 01

substitutions:
  id: switch_garden_valves_1
  update_throttle: 30s

  name_a: Sprenkler
  name_b: Büsche

packages:
  wifi: !include common/wifi_basement.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_output_a_switch.yaml
  template_b: !include common/template_output_b_switch.yaml
