# shelly rgbw2
# 02

<<: !include .shelly_rgbw2.yaml

substitutions:
  name: light_hallway_entrance
  friendly_name: Flurlicht Eingang

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    max_power: 0.3
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    max_power: 0.3
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    max_power: 0.3
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    max_power: 0.3
    id: pwm_w

light:
  - platform: monochromatic
    id: "${name}"
    name: ${friendly_name}
    output: pwm_w
    effects:
      - strobe:
          name: Pulsing
          colors:
            - state: True
              brightness: 100%
              white: 100%
              duration: 1s
            - state: False
              duration: 1s
            - state: True
              brightness: 100%
              white: 100%
              duration: 1s
            - state: False
              duration: 1s
