# gosund sp111 v1.4
# 02

substitutions:
  id: plug_livingroom_sonos_rr
  update_throttle: 30s

  name_a: Sonos (hinten rechts)

  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  template: !include common/template_sp111_switch.yaml
