# gosund sp112 v3.4
# 03

substitutions:
  id: plug_livingroom_utility
  update_throttle: 30s

  # mains
  name_a: Wohnzimmer Telefon
  # usb
  name_b: Wohnzimmer FireTV

  cf1_pin: GPIO04
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO14
  actor_pin_usb: GPIO13

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp112_v34.yaml
  template_a: !include common/template_switch_output_a.yaml
  template_b: !include common/template_switch_output_b.yaml
