# gosund sp111 v1.4
# 08

<<: !include .sp111.yaml

substitutions:
  name: plug_bedroom_tv
  friendly_name: Fernseher Schlafzimmer
  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 10s
