# gosund sp111 v1.1
# 12

substitutions:
  id: plug_basement_washer_animal
  update_throttle: 30s

  name_a: Waschmaschine Tier
  restore_mode_a: RESTORE_DEFAULT_ON

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_basement.yaml
  template: !include common/template_sp111_switch.yaml
