# gosund sp111 v1.1
# 13

<<: !include .sp111.yaml

substitutions:
  name: plug_spare_13
  friendly_name: Spare 13
  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 10s
