# gosund sp111 v1.1
# 09

substitutions:
  id: plug_basement_washer_human
  update_throttle: 30s

  name_a: Waschmaschine Mensch
  restore_mode_a: RESTORE_DEFAULT_ON

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_basement.yaml
  device: !include common/device_sp111_v11.yaml
  template: !include common/template_switch_output_a.yaml
