# gosund sp112 v2.8
# 02

substitutions:
  id: plug_bedroom_charging
  update_throttle: 30s

  name_a: Schlafzimmer Ladestation
  name_b: Schlafzimmer Ladestation USB

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp112_v28.yaml
  template_a: !include common/template_switch_output_a.yaml
  template_b: !include common/template_switch_output_b.yaml
