# gosund sp112 v3.4
# 01

<<: !include .sp112_v34.yaml

substitutions:
  name: plug_kitchen_cabinet
  friendly_name: Schranklicht
  cf1_pin: GPIO04
  output_pin: GPIO00
  status_led_pin: GPIO02
  restore_mode: RESTORE_DEFAULT_OFF
  restore_mode_usb: RESTORE_DEFAULT_ON
  update_throttle: 10s

output:
  - platform: gpio
    pin: GPIO14
    id: "${name}_actor"

light:
  - platform: binary
    name: "${friendly_name}"
    output: "${name}_actor"
    restore_mode: ${restore_mode}
