# gosund sp111 v1.4
# 06

<<: !include .sp111.yaml

substitutions:
  name: plug_office_voice_assistant
  friendly_name: Büro Google Home Mini
  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 30s
