# kitchen - cabinet light and raspi zero w 

substitutions:
  name: esphome_plug_sp112_01
  cf1_pin: GPIO04
  output_pin: GPIO00
  status_led_pin: GPIO02
  restore_mode: RESTORE_DEFAULT_OFF
  restore_mode_usb: RESTORE_DEFAULT_ON

<<: !include .sp112_v34.yaml
