# gosund sp111 v1.4
# 07

<<: !include .sp111.yaml

substitutions:
  name: sp111_plug_spare_07
  friendly_name: SP111 07
  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 30s
