# gosund sp111 v1.1
# 03

<<: !include .sp111.yaml

substitutions:
  name: plug_guestroom_printer
  friendly_name: Drucker
  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 30s
