# gosund sp112 v2.8
# 02

<<: !include .sp112_v28.yaml

substitutions:
  name: plug_bedroom_charging
  friendly_name: Schlafzimmer Ladestation
  restore_mode: RESTORE_DEFAULT_OFF
  restore_mode_usb: RESTORE_DEFAULT_ON
  update_throttle: 30s
