# v1.1 device
# basement - washer human

substitutions:
  name: esphome_plug_sp111_09
  cf1_pin: GPIO04
  output_pin: GPIO02
  status_led_pin: GPIO00
  restore_mode: RESTORE_DEFAULT_ON

<<: !include .sp111.yaml

# device located in basement
wifi:
  ssid: !secret wifi_ssid_basement
  password: !secret wifi_password
  domain: !secret wifi_domain