# gosund sp112 v2.8
# 04

<<: !include .sp112_v28.yaml

substitutions:
  name: plug_office_shelves
  friendly_name: Büro Regale
  restore_mode: RESTORE_DEFAULT_OFF
  restore_mode_usb: RESTORE_DEFAULT_ON
  update_throttle: 30s
