# gosund sp111 v1.1
# 25

substitutions:
  id: plug_guestroom_computer
  update_throttle: 30s

  name_a: Shaun

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp111.yaml
  template_a: !include common/template_output_a_switch.yaml
