# gosund sp111 v1.1
# 13

substitutions:
  id: plug_guestroom_desk
  update_throttle: 30s

  name_a: Schreibtisch
  restore_mode_a: RESTORE_DEFAULT_OFF

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp111.yaml
  template_a: !include common/template_output_a_switch.yaml
