# gosund sp111 v1.1
# 15

<<: !include .sp111.yaml

substitutions:
  name: plug_shower_voice_assistant
  friendly_name: Echo Dot Dusche
  cf1_pin: GPIO04
  output_pin: GPIO02
  status_led_pin: GPIO00
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 10s
