# gosund sp111 v1.1
# 19

<<: !include .sp111.yaml

substitutions:
  name: plug_sp111_spare_19
  friendly_name: SP111 Spare 19
  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 10s
