# v1.4 device
# livingroom - readinglight

substitutions:
  name: esphome_plug_sp111_11
  cf1_pin: GPIO14
  output_pin: GPIO00
  status_led_pin: GPIO02
  restore_mode: RESTORE_DEFAULT_OFF

<<: !include .sp111.yaml
