# gosund sp111 v1.4
# 11

substitutions:
  id: plug_livingroom_readinglight
  update_throttle: 30s

  name_a: Leselampe
  restore_mode_a: RESTORE_DEFAULT_OFF

  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_sp111_v14.yaml
  template: !include common/template_light_binary_a.yaml
