# gosund sp111 v1.4
# 04

<<: !include .sp111.yaml

substitutions:
  name: plug_bathroom_voice_assistant
  friendly_name: Badezimmer Sonos
  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 10s
