# gosund sp111 v1.4
# 01

<<: !include .sp111.yaml

substitutions:
  name: plug_livingroom_sonos_rl
  friendly_name: Sonos (hinten links)
  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  update_throttle: 10s
