# gosund sp111 v1.4
# 06

substitutions:
  id: plug_office_voice_assistant
  update_throttle: 30s

  name_a: Büro Google Home Mini

  cf1_pin: GPIO14
  state_led_pin: GPIO00
  status_led_pin: GPIO02
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  template: !include common/template_sp111_switch.yaml
