input_number:
  alarm_hour:
    name: Stunde
    icon: mdi:timer
    min: 0
    max: 23
    step: 1
  alarm_minute:
    name: Minute
    icon: mdi:timer
    min: 0
    max: 55
    step: 5

binary_sensor:
  - platform: workday
    country: !secret country
    province: !secret province

sensor:
  - platform: template
    sensors:
      alarm_time:
        friendly_name: Wecker
        value_template: '{% if states.input_number.alarm_hour.state | int | string | length == 1 %}0{% endif %}{{ states.input_number.alarm_hour.state | int }}:{% if states.input_number.alarm_minute.state | int | string | length == 1 %}0{% endif %}{{ states.input_number.alarm_minute.state | int }}'
        entity_id:
          - input_number.alarm_hour
          - input_number.alarm_minute
