switch:
  - platform: command_line
    switches:
      heating_on:
        command_on: !secret carheating_on_on
        command_off: !secret carheating_on_off
        friendly_name: Standheizung an
      heating_off:
        command_on: !secret carheating_off_on
        command_off: !secret carheating_off_off
        friendly_name: Standheizung aus

input_boolean:
  automation_carheating_winter:
  automation_carheating_reminder:

scene:
  - name: car_heating_on
    entities:
      switch.heating_on: true
  - name: car_heating_off
    entities:
      switch.heating_off: true

script:
  timer_on_off:
    sequence:
      - delay:
          seconds: 5
      - service: homeassistant.turn_off
        data:
          entity_id: switch.heating_on
  timer_off_off:
    sequence:
      - delay:
          seconds: 5
      - service: homeassistant.turn_off
        data:
          entity_id: switch.heating_off

automation:
  - alias: turn_car_heating_on
    trigger:
      platform: state
      entity_id: switch.heating_on
      to: 'on'
    action:
      service: script.turn_on
      entity_id: script.timer_on_off
  - alias: turn_car_heating_off
    trigger:
      platform: state
      entity_id: switch.heating_off
      to: 'on'
    action:
      service: script.turn_on
      entity_id: script.timer_off_off
