sensor:
  - platform: template
    sensors:
      usage_catlitter_office:
        value_template: '{% if states("input_number.count_usage_catlitter_office") | int > 0 %}{{ states("input_number.count_usage_catlitter_office") | int }} Mal, zuletzt {{ as_timestamp(states("input_datetime.last_usage_catlitter_office")) | timestamp_custom("%d.%m.%Y %H:%M") }}{% else %}Nicht benutzt{% endif %}'
      usage_catlitter_hallway:
        value_template: '{% if states("input_number.count_usage_catlitter_hallway") | int > 0 %}{{ states("input_number.count_usage_catlitter_hallway") | int }} Mal, zuletzt {{ as_timestamp(states("input_datetime.last_usage_catlitter_hallway")) | timestamp_custom("%d.%m.%Y %H:%M") }}{% else %}Nicht benutzt{% endif %}'
      usage_catlitter_guestroom:
        value_template: '{% if states("input_number.count_usage_catlitter_guestroom") | int > 0 %}{{ states("input_number.count_usage_catlitter_guestroom") | int }} Mal, zuletzt {{ as_timestamp(states("input_datetime.last_usage_catlitter_guestroom")) | timestamp_custom("%d.%m.%Y %H:%M") }}{% else %}Nicht benutzt{% endif %}'

input_datetime:
  last_usage_catlitter_office:
    has_date: true
    has_time: true
  last_usage_catlitter_hallway:
    has_date: true
    has_time: true
  last_usage_catlitter_guestroom:
    has_date: true
    has_time: true

input_number:
  count_usage_catlitter:
    initial: 0
    min: 0
    max: 100
    step: 1
  count_usage_catlitter_office:
    initial: 0
    min: 0
    max: 100
    step: 1
  count_usage_catlitter_hallway:
    initial: 0
    min: 0
    max: 100
    step: 1
  count_usage_catlitter_guestroom:
    initial: 0
    min: 0
    max: 100
    step: 1
