sensor:
  # expose climate control temperature as stand-alone sensors
  - platform: template
    sensors:
      livingroom_thermostat_current_temperature:
        friendly_name: Temperatur Wohnzimmer
        unit_of_measurement: °C
        device_class: temperature
        value_template: "{{ state_attr('climate.livingroom_thermostat', 'current_temperature') }}"
      guestroom_thermostat_current_temperature:
        friendly_name: Temperatur Gästezimmer
        unit_of_measurement: °C
        device_class: temperature
        value_template: "{{ state_attr('climate.guestroom_thermostat', 'current_temperature') }}"
      bedroom_thermostat_current_temperature:
        friendly_name: Temperatur Schlafzimmer
        unit_of_measurement: °C
        device_class: temperature
        value_template: "{{ state_attr('climate.bedroom_thermostat', 'current_temperature') }}"
      office_thermostat_current_temperature:
        friendly_name: Temperatur Büro
        unit_of_measurement: °C
        device_class: temperature
        value_template: "{{ state_attr('climate.office_thermostat', 'current_temperature') }}"
      bathroom_thermostat_current_temperature:
        friendly_name: Temperatur Bad
        unit_of_measurement: °C
        device_class: temperature
        value_template: "{{ state_attr('climate.bathroom_thermostat', 'current_temperature') }}"
      shower_thermostat_current_temperature:
        friendly_name: Temperatur Dusche
        unit_of_measurement: °C
        device_class: temperature
        value_template: "{{ state_attr('climate.shower_thermostat', 'current_temperature') }}"

  # average temperature
  # custom component https://github.com/Limych/ha-average
  - platform: average
    name: Temperatur innen (15 Minuten)
    duration:
      minutes: 15
    entities:
      - sensor.environment_inside_temperature
  - platform: average
    name: Temperatur aussen (15 Minuten)
    duration:
      minutes: 15
    entities:
      - sensor.environment_outside_temperature
  - platform: average
    name: Temperatur Garten Süd (15 Minuten)
    duration:
      minutes: 15
    entities:
      - sensor.environment_garden_south_temperature
  - platform: average
    name: Temperatur Garten West (15 Minuten)
    duration:
      minutes: 15
    entities:
      - sensor.environment_garden_west_temperature

  # average illuminance
  # custom component https://github.com/Limych/ha-average
  - platform: average
    name: Helligkeit Garten Süd (15 Minuten)
    duration:
      minutes: 15
    entities:
      - sensor.environment_garden_south_illuminance
  - platform: average
    name: Helligkeit Garten West (15 Minuten)
    duration:
      minutes: 15
    entities:
      - sensor.environment_garden_west_illuminance

  # export sun attributes to sensors
  - platform: template
    sensors:
      solar_elevation:
        friendly_name: "Elevation"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      solar_azimuth:
        friendly_name: "Azimut"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"

  # average inside temperatures
  - platform: average
    name: Innentemperatur Sued
    duration:
      minutes: 15
    entities:
      - sensor.environment_inside_temperature
      - sensor.livingroom_thermostat_current_temperature
  - platform: average
    name: Innentemperatur West
    duration:
      minutes: 15
    entities:
      - sensor.guestroom_thermostat_current_temperature
      - sensor.bedroom_thermostat_current_temperature
