sensor:
  # averages
  # custom component https://github.com/Limych/ha-average
  - platform: average
    name: Verbrauch Trockner (5 Minuten)
    duration:
      minutes: 5
    entities:
      - sensor.basement_dryer_power_usage
  - platform: average
    name: Verbrauch Waschmaschine (5 Minuten)
    duration:
      minutes: 5
    entities:
      - sensor.basement_washer_human_power_usage
  - platform: average
    name: Verbrauch Tier-Waschmaschine (5 Minuten)
    duration:
      minutes: 5
    entities:
      - sensor.basement_washer_animal_power_usage
  - platform: average
    name: Verbrauch Waschmaschine Karat (5 Minuten)
    duration:
      minutes: 5
    entities:
      - sensor.steckdose_waschmaschine_karat_power_usage
  - platform: average
    name: Verbrauch Trockner Karat (5 Minuten)
    duration:
      minutes: 5
    entities:
      - sensor.steckdose_trockner_karat_power_usage
