tplink:
  discovery: false
  # TP-Link HS110 power plugs
  switch:
    - host: !secret tplink_power_plug_washer_human
    - host: !secret tplink_power_plug_washer_animal
    - host: !secret tplink_power_plug_dryer

sensor:
  # --------------------------------------------------------------
  # WASHER HUMAN
  - platform: template
    sensors:
      # define power sensors
      washer_human_amps:
        value_template: '{{ states.switch.waschmaschine_mensch.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      washer_human_watts:
        value_template: '{{ states.switch.waschmaschine_mensch.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      washer_human_total_kwh:
        value_template: '{{ states.switch.waschmaschine_mensch.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washer_human_volts:
        value_template: '{{ states.switch.waschmaschine_mensch.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      washer_human_today_kwh:
        value_template: '{{ states.switch.waschmaschine_mensch.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      # define input select read only sensor
      washer_human_status_text:
        value_template: '{{ states.input_select.washer_human_status.state }}'

  # define history sensor for mean power usage of last 5 minutes
  - platform: statistics
    name: washer_human_consumption_last_5_mins
    entity_id: sensor.washer_human_watts
    max_age:
      minutes: 5

  # --------------------------------------------------------------
  # WASHER ANIMAL
  - platform: template
    sensors:
      # define power sensors
      washer_animal_amps:
        value_template: '{{ states.switch.waschmaschine_tier.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      washer_animal_watts:
        value_template: '{{ states.switch.waschmaschine_tier.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      washer_animal_total_kwh:
        value_template: '{{ states.switch.waschmaschine_tier.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washer_animal_volts:
        value_template: '{{ states.switch.waschmaschine_tier.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      washer_animal_today_kwh:
        value_template: '{{ states.switch.waschmaschine_tier.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      # define input select read only sensor
      washer_animal_status_text:
        value_template: '{{ states.input_select.washer_animal_status.state }}'

  # define history sensor for mean power usage of last 5 minutes
  - platform: statistics
    name: washer_animal_consumption_last_5_mins
    entity_id: sensor.washer_animal_watts
    max_age:
      minutes: 5

  # --------------------------------------------------------------
  # DRYER
  - platform: template
    sensors:
      # define power sensors
      dryer_amps:
        value_template: '{{ states.switch.trockner.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      dryer_watts:
        value_template: '{{ states.switch.trockner.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      dryer_total_kwh:
        value_template: '{{ states.switch.trockner.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      dryer_volts:
        value_template: '{{ states.switch.trockner.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      dryer_today_kwh:
        value_template: '{{ states.switch.trockner.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      # define input select read only sensor
      dryer_status_text:
        value_template: '{{ states.input_select.dryer_status.state }}'

  # define history sensor for mean power usage of last 5 minutes
  - platform: statistics
    name: dryer_consumption_last_5_mins
    entity_id: sensor.dryer_watts
    max_age:
      minutes: 5
