sensor:
  - platform: template
    sensors:
      # define input select read only sensor
      washer_human_status_text:
        value_template: '{{ states.input_select.washer_human_status.state }}'
      washer_animal_status_text:
        value_template: '{{ states.input_select.washer_animal_status.state }}'
      dryer_status_text:
        value_template: '{{ states.input_select.dryer_status.state }}'
