input_select:
  zigbee2mqtt_log_level:
    name: zigbee2MQTT log level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted

timer:
  zigbee_permit_join:
    name: zigbee2MQTT join time remaining
    duration: 120

sensor:
  - platform: mqtt
    name: zigbee2MQTT bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  - platform: mqtt
    name: zigbee2MQTT version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.version }}"
    icon: mdi:zigbee
  - platform: mqtt
    name: zigbee2MQTT coordinator version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator }}"
    icon: mdi:chip

switch:
  - platform: mqtt
    name: zigbee2MQTT allow join
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

zigbee2mqtt_networkmap:
