sensor:
  - platform: statistics
    name: Temperatur innen Schnitt 15
    entity_id: sensor.environment_inside_temperature
    max_age:
      minutes: 15
  - platform: statistics
    name: Temperatur aussen Schnitt 15
    entity_id: sensor.environment_outside_temperature
    max_age:
      minutes: 15
