sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
  - platform: template
    sensors:
      seconds_of_day:
        friendly_name: "Sekunden seit Tagesbeginn (volle Minuten)"
        value_template: "{{ now().hour * 3600 + now().minute * 60 }}"
        entity_id:
          - sensor.time
