sensor:
  - platform: waze_travel_time
    name: travel_time_jens
    origin: zone.home
    destination: zone.jens_arbeit
    region: 'EU'
  - platform: waze_travel_time
    name: travel_time_eva
    origin: zone.home
    destination: zone.eva_arbeit
    region: 'EU'
