sensor:
  - platform: nut
    name: "Eaton Ellipse Pro 650"
    host: !secret ups_host
    username: !secret ups_user
    password: !secret ups_password
    resources:
      - battery.charge
      - battery.charge.low
      - battery.runtime
      - input.voltage
      - output.voltage
      - ups.load
      - ups.mfr
      - ups.model
      - ups.power
      - ups.power.nominal
      - ups.realpower
      - ups.status
      - ups.status.display
