sensor:
# schoenaich
  - platform: abfallplus
    name: !secret abfallplus_name_bio
    key: !secret abfallplus_key
    municipality: !secret abfallplus_city
    street: !secret abfallplus_street
    trash_ids: 50
  - platform: abfallplus
    name: !secret abfallplus_name_paper
    key: !secret abfallplus_key
    municipality: !secret abfallplus_city
    street: !secret abfallplus_street
    trash_ids: 53
  - platform: abfallplus
    name: !secret abfallplus_name_waste
    key: !secret abfallplus_key
    municipality: !secret abfallplus_city
    street: !secret abfallplus_street
    trash_ids: 31
  - platform: abfallplus
    name: !secret abfallplus_name_recycling
    key: !secret abfallplus_key
    municipality: !secret abfallplus_city
    street: !secret abfallplus_street
    trash_ids: 299
